/** MIME 类型 */
type MIMEType = string
/** MIME 子类型 */
type MIMESubType = string
/** MIME 名称 */
type MIMEName = `${MIMEType}/${MIMESubType}`
/** 文件后缀名 没有点号的结构 */
type ExtName = string // `.${string}`

export const mimeMap: {
  [type: MIMEType]: { [subType: MIMESubType]: ExtName[] }
} = {
  application: {
    acrobat: ['pdf'],
    bat: ['bat'],
    cdr: ['cdr'],
    coreldraw: ['cdr'],
    csv: ['csv'],
    dbase: ['dbf'],
    dbf: ['dbf'],
    ecmascript: ['ecma', 'es'],
    emf: ['emf'],
    'epub+zip': ['epub'],
    exi: ['exi'],
    express: ['exp'],
    'font-woff': ['woff'],
    'geo+json': ['geojson', 'geojson'],
    gzip: ['gz'],
    ico: ['ico'],
    java: ['class'],
    'java-archive': ['jar', 'war', 'ear'],
    'java-byte-code': ['class'],
    'java-serialized-object': ['ser'],
    'java-vm': ['class'],
    javascript: ['js', 'mjs', 'jsm'],
    json: ['json', 'map'],
    'json-patch+json': ['json-patch'],
    json5: ['json5'],
    'jsonml+json': ['jsonml'],
    'ld+json': ['jsonld'],
    m3u: ['m3u', 'm3u8', 'vlc'],
    'manifest+json': ['webmanifest'],
    'mathml+xml': ['mathml', 'mml'],
    mbox: ['mbox'],
    mdb: ['mdb'],
    mp21: ['m21', 'mp21'],
    mp4: ['mp4s', 'm4p'],
    msaccess: ['mdb'],
    msexcel: ['xls', 'xlc', 'xll', 'xlm', 'xlw', 'xla', 'xlt', 'xld'],
    mspowerpoint: ['ppz', 'ppt', 'pps', 'pot'],
    msword: ['doc', 'dot'],
    'msword-template': ['dot'],
    nappdf: ['pdf'],
    node: ['cjs'],
    'octet-stream': [
      'bin',
      'dms',
      'lrf',
      'mar',
      'so',
      'dist',
      'distz',
      'pkg',
      'bpk',
      'dump',
      'elc',
      'deploy',
      'exe',
      'dll',
      'deb',
      'dmg',
      'iso',
      'img',
      'msi',
      'msp',
      'msm',
      'buffer',
    ],
    oda: ['oda'],
    ogg: ['ogx'],
    pdf: ['pdf'],
    photoshop: ['psd'],
    powerpoint: ['ppz', 'ppt', 'pps', 'pot'],
    ram: ['ram'],
    'raml+yaml': ['raml'],
    'rss+xml': ['rss'],
    rtf: ['rtf'],
    'schema+json': ['json'],
    sdp: ['sdp'],
    sql: ['sql'],
    tga: ['tga', 'icb', 'tpic', 'vda', 'vst'],
    toml: ['toml'],
    trig: ['trig'],
    'ttml+xml': ['ttml'],
    'vnd.adobe.flash.movie': ['swf', 'spl'],
    'vnd.android.package-archive': ['apk'],
    'vnd.apple.installer+xml': ['mpkg'],
    'vnd.apple.mpegurl': ['m3u8', 'm3u'],
    'vnd.bmi': ['bmi'],
    'vnd.coffeescript': ['coffee'],
    'vnd.dart': ['dart'],
    'vnd.dbf': ['dbf'],
    'vnd.dna': ['dna'],
    'vnd.dolby.mlp': ['mlp'],
    'vnd.efi.img': ['raw-disk-image', 'img'],
    'vnd.efi.iso': ['iso', 'iso9660'],
    'vnd.geo+json': ['geojson', 'geojson'],
    'vnd.lotus-organizer': ['org'],
    'vnd.ms-access': ['mdb'],
    'vnd.ms-asf': ['asf'],
    'vnd.ms-cab-compressed': ['cab'],
    'vnd.ms-excel': ['xls', 'xlm', 'xla', 'xlc', 'xlt', 'xlw', 'xll', 'xld'],
    'vnd.ms-excel.addin.macroenabled.12': ['xlam'],
    'vnd.ms-excel.sheet.binary.macroenabled.12': ['xlsb'],
    'vnd.ms-excel.sheet.macroenabled.12': ['xlsm'],
    'vnd.ms-excel.template.macroenabled.12': ['xltm'],
    'vnd.ms-fontobject': ['eot'],
    'vnd.ms-htmlhelp': ['chm'],
    'vnd.ms-ims': ['ims'],
    'vnd.ms-lrm': ['lrm'],
    'vnd.ms-officetheme': ['thmx'],
    'vnd.ms-outlook': ['msg'],
    'vnd.ms-pki.seccat': ['cat'],
    'vnd.ms-pki.stl': ['stl'],
    'vnd.ms-powerpoint': ['ppt', 'pps', 'pot', 'ppz'],
    'vnd.ms-powerpoint.addin.macroenabled.12': ['ppam'],
    'vnd.ms-powerpoint.presentation.macroenabled.12': ['pptm'],
    'vnd.ms-powerpoint.slide.macroenabled.12': ['sldm'],
    'vnd.ms-powerpoint.slideshow.macroenabled.12': ['ppsm'],
    'vnd.ms-powerpoint.template.macroenabled.12': ['potm'],
    'vnd.ms-project': ['mpp', 'mpt'],
    'vnd.ms-publisher': ['pub'],
    'vnd.ms-word': ['doc'],
    'vnd.ms-word.document.macroenabled.12': ['docm'],
    'vnd.ms-word.template.macroenabled.12': ['dotm'],
    'vnd.ms-works': ['wps', 'wks', 'wcm', 'wdb', 'xlr'],
    'vnd.ms-wpl': ['wpl'],
    'vnd.msaccess': ['mdb'],
    'vnd.openxmlformats-officedocument.presentationml.presentation': ['pptx'],
    'vnd.openxmlformats-officedocument.presentationml.slide': ['sldx'],
    'vnd.openxmlformats-officedocument.presentationml.slideshow': ['ppsx'],
    'vnd.openxmlformats-officedocument.presentationml.template': ['potx'],
    'vnd.openxmlformats-officedocument.spreadsheetml.sheet': ['xlsx'],
    'vnd.openxmlformats-officedocument.spreadsheetml.template': ['xltx'],
    'vnd.openxmlformats-officedocument.wordprocessingml.document': ['docx'],
    'vnd.openxmlformats-officedocument.wordprocessingml.template': ['dotx'],
    'vnd.rar': ['rar'],
    'vnd.svd': ['svd'],
    'vnd.vcx': ['vcx'],
    'vnd.youtube.yt': ['yt'],
    wasm: ['wasm'],
    widget: ['wgt'],
    wmf: ['wmf'],
    'x-7z-compressed': ['7z', '7z001'],
    'x-ace': ['ace'],
    'x-ace-compressed': ['ace'],
    'x-aportisdoc': ['pdb', 'pdc'],
    'x-asp': ['asp'],
    'x-bat': ['bat'],
    'x-bittorrent': ['torrent'],
    'x-blender': ['blend', 'blender'],
    'x-bzip': ['bz'],
    'x-bzip-compressed-tar': ['tarbz', 'tbz', 'tbz2', 'tb2'],
    'x-bzip2': ['bz2', 'boz'],
    'x-bzip2-compressed-tar': ['tarbz2', 'tbz2', 'tb2'],
    'x-bzip3': ['bz3'],
    'x-bzip3-compressed-tar': ['tarbz3', 'tbz3'],
    'x-cd-image': ['iso', 'iso9660'],
    'x-cdlink': ['vcd'],
    'x-cdr': ['cdr'],
    'x-cfs-compressed': ['cfs'],
    'x-chat': ['chat'],
    'x-chm': ['chm'],
    'x-compress': ['z'], // ['Z'],
    'x-compressed-tar': ['targz', 'tgz'],
    'x-dreamcast-rom': ['iso'],
    'x-dtbresource+xml': ['res'],
    'x-flash-video': ['flv'],
    'x-font-truetype': ['ttf'],
    'x-font-ttf': ['ttf'],
    'x-font-ttx': ['ttx'],
    'x-font-woff': ['woff'],
    'x-gzip': ['gz'],
    'x-httpd-php': ['php'],
    'x-javascript': ['js', 'jsm', 'mjs'],
    'x-linguist': ['ts'],
    'x-magicpoint': ['mgp'],
    'x-makeself': ['run'],
    'x-ms-dos-executable': ['exe'],
    'x-ms-pdb': ['pdb'],
    'x-ms-shortcut': ['lnk'],
    'x-ms-wim': ['wim', 'swm'],
    'x-ms-wmd': ['wmd'],
    'x-msdos-program': ['exe'],
    'x-msdownload': ['exe', 'dll', 'com', 'bat', 'msi'],
    'x-msexcel': ['xls', 'xlc', 'xll', 'xlm', 'xlw', 'xla', 'xlt', 'xld'],
    'x-msi': ['msi'],
    'x-msmetafile': ['wmf', 'wmz', 'emf', 'emz'],
    'x-mspowerpoint': ['ppz', 'ppt', 'pps', 'pot'],
    'x-mspublisher': ['pub'],
    'x-msschedule': ['scd'],
    'x-msterminal': ['trm'],
    'x-mswinurl': ['url'],
    'x-msword': ['doc'],
    'x-pak': ['pak'],
    'x-pdf': ['pdf'],
    'x-photoshop': ['psd'],
    'x-php': ['php', 'php3', 'php4', 'php5', 'phps'],
    'x-rar': ['rar'],
    'x-rar-compressed': ['rar'],
    'x-sh': ['sh'],
    'x-sql': ['sql'],
    'x-sqlite2': ['sqlite2'],
    'x-sqlite3': ['sqlite3'],
    'x-tar': ['tar', 'gtar', 'gem'],
    'x-targa': ['tga', 'icb', 'tpic', 'vda', 'vst'],
    'x-tarz': ['tarZ', 'taz'],
    'x-tga': ['tga', 'icb', 'tpic', 'vda', 'vst'],
    'x-tgif': ['obj'],
    'x-theme': ['theme'],
    'x-tiled-tsx': ['tsx'],
    'x-vdi-disk': ['vdi'],
    'x-vhd-disk': ['vhd', 'vpc'],
    'x-vhdx-disk': ['vhdx'],
    'x-virtualbox-hdd': ['hdd'],
    'x-virtualbox-ova': ['ova'],
    'x-virtualbox-ovf': ['ovf'],
    'x-virtualbox-vbox': ['vbox'],
    'x-virtualbox-vdi': ['vdi'],
    'x-virtualbox-vhd': ['vhd', 'vpc'],
    'x-virtualbox-vhdx': ['vhdx'],
    'x-virtualbox-vmdk': ['vmdk'],
    'x-vmdk-disk': ['vmdk'],
    'x-wais-source': ['src'],
    'x-wbfs': ['iso'],
    'x-web-app-manifest+json': ['webapp'],
    'x-wia': ['iso'],
    'x-windows-themepack': ['themepack'],
    'x-wmf': ['wmf'],
    'x-xar': ['xar', 'pkg'],
    'x-xz': ['xz'],
    'x-xz-compressed-tar': ['tarxz', 'txz'],
    'x-xzpdf': ['pdfxz'],
    'x-yaml': ['yaml', 'yml'],
    'x-zip': ['zip', 'zipx'],
    'x-zip-compressed': ['zip', 'zipx'],
    'x-zip-compressed-fb2': ['fb2zip'],
    'xhtml+xml': ['xhtml', 'xht', 'html', 'htm'],
    xml: ['xml', 'xsl', 'xsd', 'rng', 'xbl'],
    yaml: ['yaml', 'yml'],
    yang: ['yang'],
    'yin+xml': ['yin'],
    zip: ['zip', 'zipx'],
  },
  audio: {
    basic: ['au', 'snd'],
    flac: ['flac'],
    m3u: ['m3u', 'm3u8', 'vlc'],
    m4a: ['m4a', 'f4a'],
    midi: ['mid', 'midi', 'kar', 'rmi'],
    mp2: ['mp2'],
    mp3: ['mp3', 'mpga'],
    mp4: ['m4a', 'mp4a', 'f4a'],
    mpeg: ['mp3', 'mpga', 'mp2', 'mp2a', 'm2a', 'm3a'],
    mpegurl: ['m3u', 'm3u8', 'vlc'],
    ogg: ['ogg', 'oga', 'spx', 'opus'],
    vorbis: ['oga', 'ogg'],
    wav: ['wav'],
    wave: ['wav'],
    webm: ['weba'],
    wma: ['wma'],
    'x-ms-wmv': ['wmv'],
  },
  'flv-application': {
    'octet-stream': ['flv'],
  },
  font: {
    collection: ['ttc'],
    otf: ['otf'],
    ttf: ['ttf'],
    woff: ['woff'],
    woff2: ['woff2'],
  },
  image: {
    apng: ['apng', 'png'],
    avif: ['avif', 'avifs'],
    'avif-sequence': ['avif', 'avifs'],
    bmp: ['bmp', 'dib'],
    gif: ['gif'],
    heic: ['heic', 'heif', 'hif'],
    'heic-sequence': ['heics', 'heic', 'heif', 'hif'],
    heif: ['heif', 'heic', 'hif'],
    'heif-sequence': ['heifs', 'heic', 'heif', 'hif'],
    hej2k: ['hej2'],
    hsj2: ['hsj2'],
    ico: ['ico'],
    icon: ['ico'],
    jp2: ['jp2', 'jpg2'],
    jpeg: ['jpg', 'jpeg', 'jpe'],
    jpeg2000: ['jp2', 'jpg2'],
    'jpeg2000-image': ['jp2', 'jpg2'],
    jpx: ['jpx', 'jpf'],
    jxl: ['jxl'],
    pdf: ['pdf'],
    photoshop: ['psd'],
    pjpeg: ['jpg', 'jpeg', 'jpe'],
    png: ['png'],
    psd: ['psd'],
    svg: ['svg'],
    'svg+xml': ['svg', 'svgz'],
    'svg+xml-compressed': ['svgz', 'svggz'],
    tiff: ['tif', 'tiff'],
    'vnd.adobe.photoshop': ['psd'],
    'vnd.microsoft.icon': ['ico'],
    'vnd.mozilla.apng': ['apng', 'png'],
    webp: ['webp'],
  },
  message: {
    global: ['u8msg'],
    rfc822: ['eml', 'mime'],
    'vnd.wfa.wsc': ['wsc'],
  },
  model: {
    '3mf': ['3mf'],
    iges: ['igs', 'iges'],
    mesh: ['msh', 'mesh', 'silo'],
    mtl: ['mtl'],
    obj: ['obj'],
    stl: ['stl'],
    'vnd.collada+xml': ['dae'],
    'vnd.dwf': ['dwf'],
    'vnd.gdl': ['gdl'],
    'vnd.gtw': ['gtw'],
    'vnd.mts': ['mts'],
    'vnd.opengex': ['ogex'],
    'vnd.sap.vds': ['vds'],
    'vnd.usdz+zip': ['usdz'],
    'vnd.valve.source.compiled-map': ['bsp'],
    'vnd.vtu': ['vtu'],
    vrml: ['wrl', 'vrml', 'vrm'],
  },
  text: {
    'cache-manifest': ['appcache', 'manifest'],
    coffeescript: ['coffee', 'litcoffee'],
    css: ['css'],
    csv: ['csv'],
    directory: ['vcard', 'vcf', 'vct', 'gcrd'],
    ecmascript: ['es'],
    html: ['html', 'htm', 'shtml'],
    ico: ['ico'],
    jade: ['jade'],
    javascript: ['js', 'jsm', 'mjs'],
    jsx: ['jsx'],
    less: ['less'],
    markdown: ['md', 'markdown', 'mkd'],
    mathml: ['mml'],
    mdx: ['mdx'],
    org: ['org'],
    plain: ['txt', 'text', 'conf', 'def', 'list', 'log', 'in', 'ini', 'asc'],
    rss: ['rss'],
    rtf: ['rtf'],
    rust: ['rs'],
    stylus: ['stylus', 'styl'],
    troff: ['t', 'tr', 'roff', 'man', 'me', 'ms'],
    'uri-list': ['uri', 'uris', 'urls'],
    vbs: ['vbs'],
    vbscript: ['vbs'],
    vcard: ['vcard', 'vcf', 'vct', 'gcrd'],
    'x-asm': ['s', 'asm'],
    'x-blueprint': ['blp'],
    'x-c': ['c', 'cc', 'cxx', 'cpp', 'h', 'hh', 'dic'],
    'x-c++hdr': ['hh', 'hp', 'hpp', 'h++', 'hxx'],
    'x-c++src': ['cpp', 'cxx', 'cc', 'C', 'c++'],
    'x-chdr': ['h'],
    'x-cmake': ['cmake'],
    'x-cobol': ['cbl', 'cob'],
    'x-common-lisp': ['asd', 'fasl', 'lisp', 'ros'],
    'x-csharp': ['cs'],
    'x-csrc': ['c'],
    'x-csv': ['csv'],
    'x-dart': ['dart'],
    'x-dbus-service': ['service'],
    'x-diff': ['diff', 'patch'],
    'x-dsl': ['dsl'],
    'x-dsrc': ['d', 'di'],
    'x-dtd': ['dtd'],
    'x-eiffel': ['e', 'eif'],
    'x-elixir': ['ex', 'exs'],
    'x-emacs-lisp': ['el'],
    'x-erlang': ['erl'],
    'x-go': ['go'],
    'x-log': ['log'],
    'x-lua': ['lua'],
    'x-python': ['py', 'pyx', 'wsgi'],
    'x-python3': ['py', 'py3', 'py3x', 'pyi'],
    'x-sass': ['sass'],
    'x-scala': ['scala', 'sc'],
    'x-scss': ['scss'],
    'x-sfv': ['sfv'],
    'x-sh': ['sh'],
    'x-sql': ['sql'],
    'x-svhdr': ['svh'],
    'x-svsrc': ['sv'],
    'x-vala': ['vala', 'vapi'],
    'x-vcalendar': ['vcs', 'ics'],
    'x-vcard': ['vcf', 'vcard', 'vct', 'gcrd'],
    'x-verilog': ['v'],
    'x-vhdl': ['vhd', 'vhdl'],
    'x-yaml': ['yaml', 'yml'],
    'x.gcode': ['gcode'],
    xml: ['xml', 'xbl', 'xsd', 'rng'],
    'xml-external-parsed-entity': ['ent'],
    yaml: ['yaml', 'yml'],
  },
  video: {
    avi: ['avi', 'avf', 'divx'],
    divx: ['avi', 'avf', 'divx'],
    dv: ['dv'],
    fli: ['fli', 'flc'],
    flv: ['flv'],
    h261: ['h261'],
    h263: ['h263'],
    h264: ['h264'],
    jpeg: ['jpgv'],
    mp2t: ['ts', 'm2t', 'm2ts', 'mts', 'cpi', 'clpi', 'mpl', 'mpls', 'bdm', 'bdmv'],
    mp4: ['mp4', 'mp4v', 'mpg4', 'm4v', 'f4v', 'lrv'],
    mpeg: ['mpeg', 'mpg', 'mpe', 'm1v', 'm2v', 'mp2', 'vob'],
    msvideo: ['avi', 'avf', 'divx'],
    ogg: ['ogv', 'ogg'],
    quicktime: ['mov', 'qt', 'moov', 'qtvr'],
    webm: ['webm'],
    'x-matroska': ['mkv', 'mk3d', 'mks'],
    'x-ms-wmv': ['wmv'],
  },
}
export const extMap: {
  [ext: ExtName]: MIMEName[]
} = /*#__PURE__*/ (() => {
  const map: { [ext: ExtName]: MIMEName[] } = {}
  Object.keys(mimeMap).forEach((type) => {
    const subMap = mimeMap[type]
    Object.keys(subMap).forEach((subType) => {
      const extList = subMap[subType]
      extList.forEach((ext) => {
        if (!map[ext]) map[ext] = []
        map[ext].push(`${type}/${subType}`)
      })
    })
  })
  Object.keys(map).forEach((ext) => {
    map[ext].sort((a, b) => a.length - b.length)
  })
  return map
})()
// {
//   application: {
//     acrobat: ['pdf'],
//     'andrew-inset': ['ez'],
//     annodex: ['anx'],
//     applixware: ['aw'],
//     'atom+xml': ['atom'],
//     'atomcat+xml': ['atomcat'],
//     'atomdeleted+xml': ['atomdeleted'],
//     'atomsvc+xml': ['atomsvc'],
//     'atsc-dwd+xml': ['dwd'],
//     'atsc-held+xml': ['held'],
//     'atsc-rsat+xml': ['rsat'],
//     bat: ['bat'],
//     bdoc: ['bdoc'],
//     bzip2: ['bz2', 'bz'],
//     'calendar+xml': ['xcs'],
//     cbor: ['cbor'],
//     'ccxml+xml': ['ccxml'],
//     'cdfx+xml': ['cdfx'],
//     'cdmi-capability': ['cdmia'],
//     'cdmi-container': ['cdmic'],
//     'cdmi-domain': ['cdmid'],
//     'cdmi-object': ['cdmio'],
//     'cdmi-queue': ['cdmiq'],
//     cdr: ['cdr'],
//     coreldraw: ['cdr'],
//     'cpl+xml': ['cpl'],
//     csv: ['csv'],
//     'cu-seeme': ['cu'],
//     'dash+xml': ['mpd'],
//     'dash-patch+xml': ['mpp'],
//     'davmount+xml': ['davmount'],
//     dbase: ['dbf'],
//     dbf: ['dbf'],
//     dicom: ['dcm'],
//     'docbook+xml': ['dbk', 'docbook'],
//     'dssc+der': ['dssc'],
//     'dssc+xml': ['xdssc'],
//     ecmascript: ['ecma', 'es'],
//     emf: ['emf'],
//     'emma+xml': ['emma'],
//     'emotionml+xml': ['emotionml'],
//     'epub+zip': ['epub'],
//     exi: ['exi'],
//     express: ['exp'],
//     'fdt+xml': ['fdt'],
//     fits: ['fits', 'fit', 'fts'],
//     'font-tdpfr': ['pfr'],
//     'font-woff': ['woff'],
//     futuresplash: ['swf', 'spl'],
//     'geo+json': ['geojson', 'geojson'],
//     'gml+xml': ['gml'],
//     'gnunet-directory': ['gnd'],
//     gpx: ['gpx'],
//     'gpx+xml': ['gpx'],
//     gxf: ['gxf'],
//     gzip: ['gz'],
//     hjson: ['hjson'],
//     hyperstudio: ['stk'],
//     ico: ['ico'],
//     ics: ['vcs', 'ics'],
//     illustrator: ['ai'],
//     'inkml+xml': ['ink', 'inkml'],
//     ipfix: ['ipfix'],
//     'its+xml': ['its'],
//     java: ['class'],
//     'java-archive': ['jar', 'war', 'ear'],
//     'java-byte-code': ['class'],
//     'java-serialized-object': ['ser'],
//     'java-vm': ['class'],
//     javascript: ['js', 'mjs', 'jsm'],
//     'jrd+json': ['jrd'],
//     json: ['json', 'map'],
//     'json-patch+json': ['json-patch'],
//     json5: ['json5'],
//     'jsonml+json': ['jsonml'],
//     'ld+json': ['jsonld'],
//     'lgr+xml': ['lgr'],
//     'lost+xml': ['lostxml'],
//     lotus123: ['123', 'wk1', 'wk3', 'wk4', 'wks'],
//     m3u: ['m3u', 'm3u8', 'vlc'],
//     'mac-binhex40': ['hqx'],
//     'mac-compactpro': ['cpt'],
//     'mads+xml': ['mads'],
//     'manifest+json': ['webmanifest'],
//     marc: ['mrc'],
//     'marcxml+xml': ['mrcx'],
//     mathematica: ['ma', 'nb', 'mb'],
//     'mathml+xml': ['mathml', 'mml'],
//     mbox: ['mbox'],
//     mdb: ['mdb'],
//     'media-policy-dataset+xml': ['mpf'],
//     'mediaservercontrol+xml': ['mscml'],
//     'metalink+xml': ['metalink'],
//     'metalink4+xml': ['meta4'],
//     'mets+xml': ['mets'],
//     'mmt-aei+xml': ['maei'],
//     'mmt-usd+xml': ['musd'],
//     'mods+xml': ['mods'],
//     mp21: ['m21', 'mp21'],
//     mp4: ['mp4s', 'm4p'],
//     'mrb-consumer+xml': ['xdf'],
//     'mrb-publish+xml': ['xdf'],
//     'ms-tnef': ['tnef', 'tnf'],
//     msaccess: ['mdb'],
//     msexcel: ['xls', 'xlc', 'xll', 'xlm', 'xlw', 'xla', 'xlt', 'xld'],
//     mspowerpoint: ['ppz', 'ppt', 'pps', 'pot'],
//     msword: ['doc', 'dot'],
//     'msword-template': ['dot'],
//     mxf: ['mxf'],
//     'n-quads': ['nq'],
//     'n-triples': ['nt'],
//     nappdf: ['pdf'],
//     node: ['cjs'],
//     'octet-stream': [
//       'bin',
//       'dms',
//       'lrf',
//       'mar',
//       'so',
//       'dist',
//       'distz',
//       'pkg',
//       'bpk',
//       'dump',
//       'elc',
//       'deploy',
//       'exe',
//       'dll',
//       'deb',
//       'dmg',
//       'iso',
//       'img',
//       'msi',
//       'msp',
//       'msm',
//       'buffer',
//     ],
//     oda: ['oda'],
//     'oebps-package+xml': ['opf'],
//     ogg: ['ogx'],
//     'omdoc+xml': ['omdoc'],
//     onenote: ['onetoc', 'onetoc2', 'onetmp', 'onepkg'],
//     ovf: ['ova'],
//     'owl+xml': ['owx'],
//     oxps: ['oxps'],
//     'p2p-overlay+xml': ['relo'],
//     'patch-ops-error+xml': ['xer'],
//     pcap: ['pcap', 'cap', 'dmp'],
//     pdf: ['pdf'],
//     pgp: ['pgp', 'gpg', 'asc'],
//     'pgp-encrypted': ['pgp', 'gpg', 'asc'],
//     'pgp-keys': ['asc', 'skr', 'pkr', 'pgp', 'gpg', 'key'],
//     'pgp-signature': ['asc', 'sig', 'pgp', 'gpg'],
//     photoshop: ['psd'],
//     'pics-rules': ['prf'],
//     pkcs10: ['p10'],
//     pkcs12: ['p12', 'pfx'],
//     'pkcs7-mime': ['p7m', 'p7c'],
//     'pkcs7-signature': ['p7s'],
//     pkcs8: ['p8'],
//     'pkcs8-encrypted': ['p8e'],
//     'pkix-attr-cert': ['ac'],
//     'pkix-cert': ['cer'],
//     'pkix-crl': ['crl'],
//     'pkix-pkipath': ['pkipath'],
//     pkixcmp: ['pki'],
//     pls: ['pls'],
//     'pls+xml': ['pls'],
//     postscript: ['ai', 'eps', 'ps'],
//     powerpoint: ['ppz', 'ppt', 'pps', 'pot'],
//     'provenance+xml': ['provx'],
//     'prs.cww': ['cww'],
//     'pskc+xml': ['pskcxml'],
//     ram: ['ram'],
//     'raml+yaml': ['raml'],
//     'rdf+xml': ['rdf', 'owl', 'rdfs'],
//     'reginfo+xml': ['rif'],
//     'relax-ng-compact-syntax': ['rnc'],
//     'resource-lists+xml': ['rl'],
//     'resource-lists-diff+xml': ['rld'],
//     'rls-services+xml': ['rs'],
//     'route-apd+xml': ['rapd'],
//     'route-s-tsid+xml': ['sls'],
//     'route-usd+xml': ['rusd'],
//     'rpki-ghostbusters': ['gbr'],
//     'rpki-manifest': ['mft'],
//     'rpki-roa': ['roa'],
//     'rsd+xml': ['rsd'],
//     'rss+xml': ['rss'],
//     rtf: ['rtf'],
//     'sbml+xml': ['sbml'],
//     'schema+json': ['json'],
//     'scvp-cv-request': ['scq'],
//     'scvp-cv-response': ['scs'],
//     'scvp-vp-request': ['spq'],
//     'scvp-vp-response': ['spp'],
//     sdp: ['sdp'],
//     'senml+xml': ['senmlx'],
//     'sensml+xml': ['sensmlx'],
//     'set-payment-initiation': ['setpay'],
//     'set-registration-initiation': ['setreg'],
//     'shf+xml': ['shf'],
//     sieve: ['siv', 'sieve'],
//     smil: ['smil', 'smi', 'sml', 'kino'],
//     'smil+xml': ['smi', 'smil', 'sml', 'kino'],
//     'sparql-query': ['rq', 'qs'],
//     'sparql-results+xml': ['srx'],
//     sql: ['sql'],
//     srgs: ['gram'],
//     'srgs+xml': ['grxml'],
//     'sru+xml': ['sru'],
//     'ssdl+xml': ['ssdl'],
//     'ssml+xml': ['ssml'],
//     stuffit: ['sit', 'hqx'],
//     'swid+xml': ['swidtag'],
//     'tei+xml': ['tei', 'teicorpus'],
//     tga: ['tga', 'icb', 'tpic', 'vda', 'vst'],
//     'thraud+xml': ['tfi'],
//     'timestamped-data': ['tsd'],
//     toml: ['toml'],
//     trig: ['trig'],
//     'ttml+xml': ['ttml'],
//     ubjson: ['ubj'],
//     'urc-ressheet+xml': ['rsheet'],
//     'urc-targetdesc+xml': ['td'],
//     'vnd.1000minds.decision-model+xml': ['1km'],
//     'vnd.3gpp.pic-bw-large': ['plb'],
//     'vnd.3gpp.pic-bw-small': ['psb'],
//     'vnd.3gpp.pic-bw-var': ['pvb'],
//     'vnd.3gpp2.tcap': ['tcap'],
//     'vnd.3m.post-it-notes': ['pwn'],
//     'vnd.accpac.simply.aso': ['aso'],
//     'vnd.accpac.simply.imp': ['imp'],
//     'vnd.acucobol': ['acu'],
//     'vnd.acucorp': ['atc', 'acutc'],
//     'vnd.adobe.air-application-installer-package+zip': ['air'],
//     'vnd.adobe.flash.movie': ['swf', 'spl'],
//     'vnd.adobe.formscentral.fcdt': ['fcdt'],
//     'vnd.adobe.fxp': ['fxp', 'fxpl'],
//     'vnd.adobe.illustrator': ['ai'],
//     'vnd.adobe.xdp+xml': ['xdp'],
//     'vnd.adobe.xfdf': ['xfdf'],
//     'vnd.age': ['age'],
//     'vnd.ahead.space': ['ahead'],
//     'vnd.airzip.filesecure.azf': ['azf'],
//     'vnd.airzip.filesecure.azs': ['azs'],
//     'vnd.amazon.ebook': ['azw'],
//     'vnd.amazon.mobi8-ebook': ['azw3', 'kfx'],
//     'vnd.americandynamics.acc': ['acc'],
//     'vnd.amiga.ami': ['ami'],
//     'vnd.android.package-archive': ['apk'],
//     'vnd.anser-web-certificate-issue-initiation': ['cii'],
//     'vnd.anser-web-funds-transfer-initiation': ['fti'],
//     'vnd.antix.game-component': ['atx'],
//     'vnd.appimage': ['appimage'],
//     'vnd.apple.installer+xml': ['mpkg'],
//     'vnd.apple.keynote': ['key', 'keynote'],
//     'vnd.apple.mpegurl': ['m3u8', 'm3u'],
//     'vnd.apple.numbers': ['numbers'],
//     'vnd.apple.pages': ['pages'],
//     'vnd.apple.pkpass': ['pkpass'],
//     'vnd.aristanetworks.swi': ['swi'],
//     'vnd.astraea-software.iota': ['iota'],
//     'vnd.audiograph': ['aep'],
//     'vnd.balsamiq.bmml+xml': ['bmml'],
//     'vnd.blueice.multipass': ['mpm'],
//     'vnd.bmi': ['bmi'],
//     'vnd.businessobjects': ['rep'],
//     'vnd.chemdraw+xml': ['cdxml'],
//     'vnd.chess-pgn': ['pgn'],
//     'vnd.chipnuts.karaoke-mmd': ['mmd'],
//     'vnd.cinderella': ['cdy'],
//     'vnd.citationstyles.style+xml': ['csl'],
//     'vnd.claymore': ['cla'],
//     'vnd.cloanto.rp9': ['rp9'],
//     'vnd.clonk.c4group': ['c4g', 'c4d', 'c4f', 'c4p', 'c4u'],
//     'vnd.cluetrust.cartomobile-config': ['c11amc'],
//     'vnd.cluetrust.cartomobile-config-pkg': ['c11amz'],
//     'vnd.coffeescript': ['coffee'],
//     'vnd.comicbook+zip': ['cbz'],
//     'vnd.comicbook-rar': ['cbr'],
//     'vnd.commonspace': ['csp'],
//     'vnd.contact.cmsg': ['cdbcmsg'],
//     'vnd.corel-draw': ['cdr'],
//     'vnd.cosmocaller': ['cmc'],
//     'vnd.crick.clicker': ['clkx'],
//     'vnd.crick.clicker.keyboard': ['clkk'],
//     'vnd.crick.clicker.palette': ['clkp'],
//     'vnd.crick.clicker.template': ['clkt'],
//     'vnd.crick.clicker.wordbank': ['clkw'],
//     'vnd.criticaltools.wbs+xml': ['wbs'],
//     'vnd.ctc-posml': ['pml'],
//     'vnd.cups-ppd': ['ppd'],
//     'vnd.curl.car': ['car'],
//     'vnd.curl.pcurl': ['pcurl'],
//     'vnd.dart': ['dart'],
//     'vnd.data-vision.rdz': ['rdz'],
//     'vnd.dbf': ['dbf'],
//     'vnd.debian.binary-package': ['deb', 'udeb'],
//     'vnd.dece.data': ['uvf', 'uvvf', 'uvd', 'uvvd'],
//     'vnd.dece.ttml+xml': ['uvt', 'uvvt'],
//     'vnd.dece.unspecified': ['uvx', 'uvvx'],
//     'vnd.dece.zip': ['uvz', 'uvvz'],
//     'vnd.denovo.fcselayout-link': ['fe_launch'],
//     'vnd.dna': ['dna'],
//     'vnd.dolby.mlp': ['mlp'],
//     'vnd.dpgraph': ['dpg'],
//     'vnd.dreamfactory': ['dfac'],
//     'vnd.ds-keypoint': ['kpxx'],
//     'vnd.dvb.ait': ['ait'],
//     'vnd.dvb.service': ['svc'],
//     'vnd.dynageo': ['geo'],
//     'vnd.ecowin.chart': ['mag'],
//     'vnd.efi.img': ['raw-disk-image', 'img'],
//     'vnd.efi.iso': ['iso', 'iso9660'],
//     'vnd.emusic-emusic_package': ['emp'],
//     'vnd.enliven': ['nml'],
//     'vnd.epson.esf': ['esf'],
//     'vnd.epson.msf': ['msf'],
//     'vnd.epson.quickanime': ['qam'],
//     'vnd.epson.salt': ['slt'],
//     'vnd.epson.ssf': ['ssf'],
//     'vnd.eszigno3+xml': ['es3', 'et3'],
//     'vnd.etsi.asic-e+zip': ['asice'],
//     'vnd.ezpix-album': ['ez2'],
//     'vnd.ezpix-package': ['ez3'],
//     'vnd.fdf': ['fdf'],
//     'vnd.fdsn.mseed': ['mseed'],
//     'vnd.fdsn.seed': ['seed', 'dataless'],
//     'vnd.flatpak': ['flatpak', 'xdgapp'],
//     'vnd.flatpak.ref': ['flatpakref'],
//     'vnd.flatpak.repo': ['flatpakrepo'],
//     'vnd.flographit': ['gph'],
//     'vnd.fluxtime.clip': ['ftc'],
//     'vnd.framemaker': ['fm', 'frame', 'maker', 'book'],
//     'vnd.frogans.fnc': ['fnc'],
//     'vnd.frogans.ltf': ['ltf'],
//     'vnd.fsc.weblaunch': ['fsc'],
//     'vnd.fujitsu.oasys': ['oas'],
//     'vnd.fujitsu.oasys2': ['oa2'],
//     'vnd.fujitsu.oasys3': ['oa3'],
//     'vnd.fujitsu.oasysgp': ['fg5'],
//     'vnd.fujitsu.oasysprs': ['bh2'],
//     'vnd.fujixerox.ddd': ['ddd'],
//     'vnd.fujixerox.docuworks': ['xdw'],
//     'vnd.fujixerox.docuworks.binder': ['xbd'],
//     'vnd.fuzzysheet': ['fzs'],
//     'vnd.genomatix.tuxedo': ['txd'],
//     'vnd.geo+json': ['geojson', 'geojson'],
//     'vnd.geogebra.file': ['ggb'],
//     'vnd.geogebra.tool': ['ggt'],
//     'vnd.geometry-explorer': ['gex', 'gre'],
//     'vnd.geonext': ['gxt'],
//     'vnd.geoplan': ['g2w'],
//     'vnd.geospace': ['g3w'],
//     'vnd.gerber': ['gbr'],
//     'vnd.gmx': ['gmx'],
//     'vnd.google-apps.document': ['gdoc'],
//     'vnd.google-apps.presentation': ['gslides'],
//     'vnd.google-apps.spreadsheet': ['gsheet'],
//     'vnd.google-earth.kml+xml': ['kml'],
//     'vnd.google-earth.kmz': ['kmz'],
//     'vnd.grafeq': ['gqf', 'gqs'],
//     'vnd.groove-account': ['gac'],
//     'vnd.groove-help': ['ghf'],
//     'vnd.groove-identity-message': ['gim'],
//     'vnd.groove-injector': ['grv'],
//     'vnd.groove-tool-message': ['gtm'],
//     'vnd.groove-tool-template': ['tpl'],
//     'vnd.groove-vcard': ['vcg'],
//     'vnd.haansoft-hwp': ['hwp'],
//     'vnd.haansoft-hwt': ['hwt'],
//     'vnd.hal+xml': ['hal'],
//     'vnd.handheld-entertainment+xml': ['zmm'],
//     'vnd.hbci': ['hbci'],
//     'vnd.hhe.lesson-player': ['les'],
//     'vnd.hp-hpgl': ['hpgl'],
//     'vnd.hp-hpid': ['hpid'],
//     'vnd.hp-hps': ['hps'],
//     'vnd.hp-jlyt': ['jlt'],
//     'vnd.hp-pcl': ['pcl'],
//     'vnd.hp-pclxl': ['pclxl'],
//     'vnd.hydrostatix.sof-data': ['sfd-hdstx'],
//     'vnd.ibm.minipay': ['mpy'],
//     'vnd.ibm.modcap': ['afp', 'listafp', 'list3820'],
//     'vnd.ibm.rights-management': ['irm'],
//     'vnd.ibm.secure-container': ['sc'],
//     'vnd.iccprofile': ['icc', 'icm'],
//     'vnd.igloader': ['igl'],
//     'vnd.immervision-ivp': ['ivp'],
//     'vnd.immervision-ivu': ['ivu'],
//     'vnd.insors.igm': ['igm'],
//     'vnd.intercon.formnet': ['xpw', 'xpx'],
//     'vnd.intergeo': ['i2g'],
//     'vnd.intu.qbo': ['qbo'],
//     'vnd.intu.qfx': ['qfx'],
//     'vnd.ipunplugged.rcprofile': ['rcprofile'],
//     'vnd.irepository.package+xml': ['irp'],
//     'vnd.is-xpr': ['xpr'],
//     'vnd.isac.fcs': ['fcs'],
//     'vnd.jam': ['jam'],
//     'vnd.jcp.javame.midlet-rms': ['rms'],
//     'vnd.jisp': ['jisp'],
//     'vnd.joost.joda-archive': ['joda'],
//     'vnd.kahootz': ['ktz', 'ktr'],
//     'vnd.kde.karbon': ['karbon'],
//     'vnd.kde.kchart': ['chrt'],
//     'vnd.kde.kformula': ['kfo'],
//     'vnd.kde.kivio': ['flw'],
//     'vnd.kde.kontour': ['kon'],
//     'vnd.kde.kpresenter': ['kpr', 'kpt'],
//     'vnd.kde.kspread': ['ksp'],
//     'vnd.kde.kword': ['kwd', 'kwt'],
//     'vnd.kenameaapp': ['htke'],
//     'vnd.kidspiration': ['kia'],
//     'vnd.kinar': ['kne', 'knp'],
//     'vnd.koan': ['skp', 'skd', 'skt', 'skm'],
//     'vnd.kodak-descriptor': ['sse'],
//     'vnd.las.las+xml': ['lasxml'],
//     'vnd.llamagraphics.life-balance.desktop': ['lbd'],
//     'vnd.llamagraphics.life-balance.exchange+xml': ['lbe'],
//     'vnd.lotus-1-2-3': ['123', 'wk1', 'wk3', 'wk4', 'wks'],
//     'vnd.lotus-approach': ['apr'],
//     'vnd.lotus-freelance': ['pre'],
//     'vnd.lotus-notes': ['nsf'],
//     'vnd.lotus-organizer': ['org'],
//     'vnd.lotus-screencam': ['scm'],
//     'vnd.lotus-wordpro': ['lwp'],
//     'vnd.macports.portpkg': ['portpkg'],
//     'vnd.mapbox-vector-tile': ['mvt'],
//     'vnd.mcd': ['mcd'],
//     'vnd.medcalcdata': ['mc1'],
//     'vnd.mediastation.cdkey': ['cdkey'],
//     'vnd.mfer': ['mwf'],
//     'vnd.mfmp': ['mfm'],
//     'vnd.micrografx.flo': ['flo'],
//     'vnd.micrografx.igx': ['igx'],
//     'vnd.mif': ['mif'],
//     'vnd.mobius.daf': ['daf'],
//     'vnd.mobius.dis': ['dis'],
//     'vnd.mobius.mbk': ['mbk'],
//     'vnd.mobius.mqy': ['mqy'],
//     'vnd.mobius.msl': ['msl'],
//     'vnd.mobius.plc': ['plc'],
//     'vnd.mobius.txf': ['txf'],
//     'vnd.mophun.application': ['mpn'],
//     'vnd.mophun.certificate': ['mpc'],
//     'vnd.mozilla.xul+xml': ['xul'],
//     'vnd.ms-3mfdocument': ['3mf'],
//     'vnd.ms-access': ['mdb'],
//     'vnd.ms-artgalry': ['cil'],
//     'vnd.ms-asf': ['asf'],
//     'vnd.ms-cab-compressed': ['cab'],
//     'vnd.ms-excel': ['xls', 'xlm', 'xla', 'xlc', 'xlt', 'xlw', 'xll', 'xld'],
//     'vnd.ms-excel.addin.macroenabled.12': ['xlam'],
//     'vnd.ms-excel.sheet.binary.macroenabled.12': ['xlsb'],
//     'vnd.ms-excel.sheet.macroenabled.12': ['xlsm'],
//     'vnd.ms-excel.template.macroenabled.12': ['xltm'],
//     'vnd.ms-fontobject': ['eot'],
//     'vnd.ms-htmlhelp': ['chm'],
//     'vnd.ms-ims': ['ims'],
//     'vnd.ms-lrm': ['lrm'],
//     'vnd.ms-officetheme': ['thmx'],
//     'vnd.ms-outlook': ['msg'],
//     'vnd.ms-pki.seccat': ['cat'],
//     'vnd.ms-pki.stl': ['stl'],
//     'vnd.ms-powerpoint': ['ppt', 'pps', 'pot', 'ppz'],
//     'vnd.ms-powerpoint.addin.macroenabled.12': ['ppam'],
//     'vnd.ms-powerpoint.presentation.macroenabled.12': ['pptm'],
//     'vnd.ms-powerpoint.slide.macroenabled.12': ['sldm'],
//     'vnd.ms-powerpoint.slideshow.macroenabled.12': ['ppsm'],
//     'vnd.ms-powerpoint.template.macroenabled.12': ['potm'],
//     'vnd.ms-project': ['mpp', 'mpt'],
//     'vnd.ms-publisher': ['pub'],
//     'vnd.ms-tnef': ['tnef', 'tnf'],
//     'vnd.ms-visio.drawing.macroenabled.main+xml': ['vsdm'],
//     'vnd.ms-visio.drawing.main+xml': ['vsdx'],
//     'vnd.ms-visio.stencil.macroenabled.main+xml': ['vssm'],
//     'vnd.ms-visio.stencil.main+xml': ['vssx'],
//     'vnd.ms-visio.template.macroenabled.main+xml': ['vstm'],
//     'vnd.ms-visio.template.main+xml': ['vstx'],
//     'vnd.ms-word': ['doc'],
//     'vnd.ms-word.document.macroenabled.12': ['docm'],
//     'vnd.ms-word.template.macroenabled.12': ['dotm'],
//     'vnd.ms-works': ['wps', 'wks', 'wcm', 'wdb', 'xlr'],
//     'vnd.ms-wpl': ['wpl'],
//     'vnd.ms-xpsdocument': ['xps'],
//     'vnd.msaccess': ['mdb'],
//     'vnd.mseq': ['mseq'],
//     'vnd.musician': ['mus'],
//     'vnd.muvee.style': ['msty'],
//     'vnd.mynfc': ['taglet'],
//     'vnd.neurolanguage.nlu': ['nlu'],
//     'vnd.nintendo.snes.rom': ['sfc', 'smc'],
//     'vnd.nitf': ['ntf', 'nitf'],
//     'vnd.noblenet-directory': ['nnd'],
//     'vnd.noblenet-sealer': ['nns'],
//     'vnd.noblenet-web': ['nnw'],
//     'vnd.nokia.n-gage.ac+xml': ['ac'],
//     'vnd.nokia.n-gage.data': ['ngdat'],
//     'vnd.nokia.n-gage.symbian.install': ['n-gage'],
//     'vnd.nokia.radio-preset': ['rpst'],
//     'vnd.nokia.radio-presets': ['rpss'],
//     'vnd.novadigm.edm': ['edm'],
//     'vnd.novadigm.edx': ['edx'],
//     'vnd.novadigm.ext': ['ext'],
//     'vnd.oasis.docbook+xml': ['dbk', 'docbook'],
//     'vnd.oasis.opendocument.chart': ['odc'],
//     'vnd.oasis.opendocument.chart-template': ['otc'],
//     'vnd.oasis.opendocument.database': ['odb'],
//     'vnd.oasis.opendocument.formula': ['odf'],
//     'vnd.oasis.opendocument.formula-template': ['odft', 'otf'],
//     'vnd.oasis.opendocument.graphics': ['odg'],
//     'vnd.oasis.opendocument.graphics-flat-xml': ['fodg'],
//     'vnd.oasis.opendocument.graphics-template': ['otg'],
//     'vnd.oasis.opendocument.image': ['odi'],
//     'vnd.oasis.opendocument.image-template': ['oti'],
//     'vnd.oasis.opendocument.presentation': ['odp'],
//     'vnd.oasis.opendocument.presentation-flat-xml': ['fodp'],
//     'vnd.oasis.opendocument.presentation-template': ['otp'],
//     'vnd.oasis.opendocument.spreadsheet': ['ods'],
//     'vnd.oasis.opendocument.spreadsheet-flat-xml': ['fods'],
//     'vnd.oasis.opendocument.spreadsheet-template': ['ots'],
//     'vnd.oasis.opendocument.text': ['odt'],
//     'vnd.oasis.opendocument.text-flat-xml': ['fodt'],
//     'vnd.oasis.opendocument.text-master': ['odm'],
//     'vnd.oasis.opendocument.text-template': ['ott'],
//     'vnd.oasis.opendocument.text-web': ['oth'],
//     'vnd.olpc-sugar': ['xo'],
//     'vnd.oma.dd2+xml': ['dd2'],
//     'vnd.openblox.game+xml': ['obgx'],
//     'vnd.openofficeorg.extension': ['oxt'],
//     'vnd.openstreetmap.data+xml': ['osm'],
//     'vnd.openxmlformats-officedocument.presentationml.presentation': ['pptx'],
//     'vnd.openxmlformats-officedocument.presentationml.slide': ['sldx'],
//     'vnd.openxmlformats-officedocument.presentationml.slideshow': ['ppsx'],
//     'vnd.openxmlformats-officedocument.presentationml.template': ['potx'],
//     'vnd.openxmlformats-officedocument.spreadsheetml.sheet': ['xlsx'],
//     'vnd.openxmlformats-officedocument.spreadsheetml.template': ['xltx'],
//     'vnd.openxmlformats-officedocument.wordprocessingml.document': ['docx'],
//     'vnd.openxmlformats-officedocument.wordprocessingml.template': ['dotx'],
//     'vnd.osgeo.mapguide.package': ['mgp'],
//     'vnd.osgi.dp': ['dp'],
//     'vnd.osgi.subsystem': ['esa'],
//     'vnd.palm': ['pdb', 'pqa', 'oprc', 'prc'],
//     'vnd.pawaafile': ['paw'],
//     'vnd.pg.format': ['str'],
//     'vnd.pg.osasli': ['ei6'],
//     'vnd.picsel': ['efif'],
//     'vnd.pmi.widget': ['wg'],
//     'vnd.pocketlearn': ['plf'],
//     'vnd.powerbuilder6': ['pbd'],
//     'vnd.previewsystems.box': ['box'],
//     'vnd.proteus.magazine': ['mgz'],
//     'vnd.publishare-delta-tree': ['qps'],
//     'vnd.pvi.ptid1': ['ptid'],
//     'vnd.quark.quarkxpress': ['qxd', 'qxt', 'qwd', 'qwt', 'qxl', 'qxb'],
//     'vnd.rar': ['rar'],
//     'vnd.realvnc.bed': ['bed'],
//     'vnd.recordare.musicxml': ['mxl'],
//     'vnd.recordare.musicxml+xml': ['musicxml'],
//     'vnd.rig.cryptonote': ['cryptonote'],
//     'vnd.rim.cod': ['cod'],
//     'vnd.rn-realmedia': ['rm', 'rmj', 'rmm', 'rms', 'rmx', 'rmvb'],
//     'vnd.rn-realmedia-vbr': ['rmvb', 'rm', 'rmj', 'rmm', 'rms', 'rmx'],
//     'vnd.route66.link66+xml': ['link66'],
//     'vnd.sailingtracker.track': ['st'],
//     'vnd.sdp': ['sdp'],
//     'vnd.seemail': ['see'],
//     'vnd.sema': ['sema'],
//     'vnd.semd': ['semd'],
//     'vnd.semf': ['semf'],
//     'vnd.shana.informed.formdata': ['ifm'],
//     'vnd.shana.informed.formtemplate': ['itp'],
//     'vnd.shana.informed.interchange': ['iif'],
//     'vnd.shana.informed.package': ['ipk'],
//     'vnd.simtech-mindmapper': ['twd', 'twds'],
//     'vnd.smaf': ['mmf', 'smaf'],
//     'vnd.smart.teacher': ['teacher'],
//     'vnd.snap': ['snap'],
//     'vnd.software602.filler.form+xml': ['fo'],
//     'vnd.solent.sdkm+xml': ['sdkm', 'sdkd'],
//     'vnd.spotfire.dxp': ['dxp'],
//     'vnd.spotfire.sfs': ['sfs'],
//     'vnd.sqlite3': ['sqlite3'],
//     'vnd.squashfs': ['sqsh'],
//     'vnd.stardivision.calc': ['sdc'],
//     'vnd.stardivision.chart': ['sds'],
//     'vnd.stardivision.draw': ['sda'],
//     'vnd.stardivision.impress': ['sdd', 'sdp'],
//     'vnd.stardivision.mail': ['smd'],
//     'vnd.stardivision.math': ['smf'],
//     'vnd.stardivision.writer': ['sdw', 'vor', 'sgl'],
//     'vnd.stardivision.writer-global': ['sgl', 'sdw', 'vor'],
//     'vnd.stepmania.package': ['smzip'],
//     'vnd.stepmania.stepchart': ['sm'],
//     'vnd.sun.wadl+xml': ['wadl'],
//     'vnd.sun.xml.base': ['odb'],
//     'vnd.sun.xml.calc': ['sxc'],
//     'vnd.sun.xml.calc.template': ['stc'],
//     'vnd.sun.xml.draw': ['sxd'],
//     'vnd.sun.xml.draw.template': ['std'],
//     'vnd.sun.xml.impress': ['sxi'],
//     'vnd.sun.xml.impress.template': ['sti'],
//     'vnd.sun.xml.math': ['sxm'],
//     'vnd.sun.xml.writer': ['sxw'],
//     'vnd.sun.xml.writer.global': ['sxg'],
//     'vnd.sun.xml.writer.template': ['stw'],
//     'vnd.sus-calendar': ['sus', 'susp'],
//     'vnd.svd': ['svd'],
//     'vnd.symbian.install': ['sis', 'sisx'],
//     'vnd.syncml+xml': ['xsm'],
//     'vnd.syncml.dm+wbxml': ['bdm'],
//     'vnd.syncml.dm+xml': ['xdm'],
//     'vnd.syncml.dmddf+xml': ['ddf'],
//     'vnd.tao.intent-module-archive': ['tao'],
//     'vnd.tcpdump.pcap': ['pcap', 'cap', 'dmp'],
//     'vnd.tmobile-livetv': ['tmo'],
//     'vnd.trid.tpt': ['tpt'],
//     'vnd.triscape.mxs': ['mxs'],
//     'vnd.trueapp': ['tra'],
//     'vnd.truedoc': ['pfr'],
//     'vnd.ufdl': ['ufd', 'ufdl'],
//     'vnd.uiq.theme': ['utz'],
//     'vnd.umajin': ['umj'],
//     'vnd.unity': ['unityweb'],
//     'vnd.uoml+xml': ['uoml'],
//     'vnd.vcx': ['vcx'],
//     'vnd.visio': ['vsd', 'vst', 'vss', 'vsw'],
//     'vnd.visionary': ['vis'],
//     'vnd.vsf': ['vsf'],
//     'vnd.wap.wbxml': ['wbxml'],
//     'vnd.wap.wmlc': ['wmlc'],
//     'vnd.wap.wmlscriptc': ['wmlsc'],
//     'vnd.webturbo': ['wtb'],
//     'vnd.wolfram.player': ['nbp'],
//     'vnd.wordperfect': ['wpd', 'wp', 'wp4', 'wp5', 'wp6', 'wpp'],
//     'vnd.wqd': ['wqd'],
//     'vnd.wt.stf': ['stf'],
//     'vnd.xara': ['xar'],
//     'vnd.xdgapp': ['flatpak', 'xdgapp'],
//     'vnd.xfdl': ['xfdl'],
//     'vnd.yamaha.hv-dic': ['hvd'],
//     'vnd.yamaha.hv-script': ['hvs'],
//     'vnd.yamaha.hv-voice': ['hvp'],
//     'vnd.yamaha.openscoreformat': ['osf'],
//     'vnd.yamaha.openscoreformat.osfpvg+xml': ['osfpvg'],
//     'vnd.yamaha.smaf-audio': ['saf'],
//     'vnd.yamaha.smaf-phrase': ['spf'],
//     'vnd.yellowriver-custom-menu': ['cmp'],
//     'vnd.youtube.yt': ['yt'],
//     'vnd.zul': ['zir', 'zirz'],
//     'vnd.zzazz.deck+xml': ['zaz'],
//     'voicexml+xml': ['vxml'],
//     wasm: ['wasm'],
//     'watcherinfo+xml': ['wif'],
//     widget: ['wgt'],
//     winhlp: ['hlp'],
//     wk1: ['123', 'wk1', 'wk3', 'wk4', 'wks'],
//     wmf: ['wmf'],
//     wordperfect: ['wp', 'wp4', 'wp5', 'wp6', 'wpd', 'wpp'],
//     'wsdl+xml': ['wsdl'],
//     'wspolicy+xml': ['wspolicy'],
//     wwf: ['wwf'],
//     'x-123': ['123', 'wk1', 'wk3', 'wk4', 'wks'],
//     'x-7z-compressed': ['7z', '7z001'],
//     'x-abiword': ['abw', 'abwCRASHED', 'abwgz', 'zabw'],
//     'x-ace': ['ace'],
//     'x-ace-compressed': ['ace'],
//     'x-alz': ['alz'],
//     'x-amiga-disk-format': ['adf'],
//     'x-amipro': ['sam'],
//     'x-annodex': ['anx'],
//     'x-aportisdoc': ['pdb', 'pdc'],
//     'x-apple-diskimage': ['dmg'],
//     'x-apple-systemprofiler+xml': ['spx'],
//     'x-appleworks-document': ['cwk'],
//     'x-applix-spreadsheet': ['as'],
//     'x-applix-word': ['aw'],
//     'x-archive': ['a', 'ar'],
//     'x-arj': ['arj'],
//     'x-asar': ['asar'],
//     'x-asp': ['asp'],
//     'x-atari-2600-rom': ['a26'],
//     'x-atari-7800-rom': ['a78'],
//     'x-atari-lynx-rom': ['lnx'],
//     'x-authorware-bin': ['aab', 'x32', 'u32', 'vox'],
//     'x-authorware-map': ['aam'],
//     'x-authorware-seg': ['aas'],
//     'x-awk': ['awk'],
//     'x-bat': ['bat'],
//     'x-bcpio': ['bcpio'],
//     'x-bdoc': ['bdoc'],
//     'x-bittorrent': ['torrent'],
//     'x-blender': ['blend', 'BLEND', 'blender'],
//     'x-blorb': ['blb', 'blorb'],
//     'x-bps-patch': ['bps'],
//     'x-bsdiff': ['bsdiff'],
//     'x-bz2': ['bz2'],
//     'x-bzdvi': ['dvibz2'],
//     'x-bzip': ['bz'],
//     'x-bzip-compressed-tar': ['tarbz', 'tbz', 'tbz2', 'tb2'],
//     'x-bzip2': ['bz2', 'boz'],
//     'x-bzip2-compressed-tar': ['tarbz2', 'tbz2', 'tb2'],
//     'x-bzip3': ['bz3'],
//     'x-bzip3-compressed-tar': ['tarbz3', 'tbz3'],
//     'x-bzpdf': ['pdfbz2'],
//     'x-bzpostscript': ['psbz2'],
//     'x-cb7': ['cb7'],
//     'x-cbr': ['cbr', 'cba', 'cbt', 'cbz', 'cb7'],
//     'x-cbt': ['cbt'],
//     'x-cbz': ['cbz'],
//     'x-ccmx': ['ccmx'],
//     'x-cd-image': ['iso', 'iso9660'],
//     'x-cdlink': ['vcd'],
//     'x-cdr': ['cdr'],
//     'x-cdrdao-toc': ['toc'],
//     'x-cfs-compressed': ['cfs'],
//     'x-chat': ['chat'],
//     'x-chess-pgn': ['pgn'],
//     'x-chm': ['chm'],
//     'x-chrome-extension': ['crx'],
//     'x-cisco-vpn-settings': ['pcf'],
//     'x-cocoa': ['cco'],
//     'x-compress': ['Z'],
//     'x-compressed-iso': ['cso'],
//     'x-compressed-tar': ['targz', 'tgz'],
//     'x-conference': ['nsc'],
//     'x-coreldraw': ['cdr'],
//     'x-cpio': ['cpio'],
//     'x-cpio-compressed': ['cpiogz'],
//     'x-csh': ['csh'],
//     'x-cue': ['cue'],
//     'x-dar': ['dar'],
//     'x-dbase': ['dbf'],
//     'x-dbf': ['dbf'],
//     'x-dc-rom': ['dc'],
//     'x-deb': ['deb', 'udeb'],
//     'x-debian-package': ['deb', 'udeb'],
//     'x-designer': ['ui'],
//     'x-desktop': ['desktop', 'kdelnk'],
//     'x-dgc-compressed': ['dgc'],
//     'x-dia-diagram': ['dia'],
//     'x-dia-shape': ['shape'],
//     'x-director': ['dir', 'dcr', 'dxr', 'cst', 'cct', 'cxt', 'w3d', 'fgd', 'swa'],
//     'x-discjuggler-cd-image': ['cdi'],
//     'x-docbook+xml': ['dbk', 'docbook'],
//     'x-doom': ['wad'],
//     'x-doom-wad': ['wad'],
//     'x-dreamcast-rom': ['iso'],
//     'x-dtbncx+xml': ['ncx'],
//     'x-dtbook+xml': ['dtb'],
//     'x-dtbresource+xml': ['res'],
//     'x-dvi': ['dvi'],
//     'x-e-theme': ['etheme'],
//     'x-egon': ['egon'],
//     'x-emf': ['emf'],
//     'x-envoy': ['evy'],
//     'x-eris-link+cbor': ['eris'],
//     'x-eva': ['eva'],
//     'x-excellon': ['drl'],
//     'x-fd-file': ['fd', 'qd'],
//     'x-fds-disk': ['fds'],
//     'x-fictionbook': ['fb2'],
//     'x-fictionbook+xml': ['fb2'],
//     'x-fishscript': ['fish'],
//     'x-flash-video': ['flv'],
//     'x-fluid': ['fl'],
//     'x-font-afm': ['afm'],
//     'x-font-bdf': ['bdf'],
//     'x-font-ghostscript': ['gsf'],
//     'x-font-linux-psf': ['psf'],
//     'x-font-otf': ['otf'],
//     'x-font-pcf': ['pcf', 'pcfZ', 'pcfgz'],
//     'x-font-snf': ['snf'],
//     'x-font-speedo': ['spd'],
//     'x-font-truetype': ['ttf'],
//     'x-font-ttf': ['ttf'],
//     'x-font-ttx': ['ttx'],
//     'x-font-type1': ['pfa', 'pfb', 'pfm', 'afm', 'gsf'],
//     'x-font-woff': ['woff'],
//     'x-frame': ['fm'],
//     'x-freearc': ['arc'],
//     'x-futuresplash': ['spl'],
//     'x-gameboy-color-rom': ['gbc', 'cgb'],
//     'x-gameboy-rom': ['gb', 'sgb'],
//     'x-gamecube-iso-image': ['iso'],
//     'x-gamecube-rom': ['iso'],
//     'x-gamegear-rom': ['gg'],
//     'x-gba-rom': ['gba', 'agb'],
//     'x-gca-compressed': ['gca'],
//     'x-gd-rom-cue': ['gdi'],
//     'x-gdscript': ['gd'],
//     'x-gedcom': ['ged', 'gedcom'],
//     'x-genesis-32x-rom': ['32x', 'mdx'],
//     'x-genesis-rom': ['gen', 'smd', 'sgd'],
//     'x-gerber': ['gbr'],
//     'x-gerber-job': ['gbrjob'],
//     'x-gettext': ['po'],
//     'x-gettext-translation': ['gmo', 'mo'],
//     'x-glade': ['glade'],
//     'x-glulx': ['ulx'],
//     'x-gnome-app-info': ['desktop', 'kdelnk'],
//     'x-gnucash': ['gnucash', 'gnc', 'xac'],
//     'x-gnumeric': ['gnumeric'],
//     'x-gnuplot': ['gp', 'gplt', 'gnuplot'],
//     'x-go-sgf': ['sgf'],
//     'x-godot-resource': ['res', 'tres'],
//     'x-godot-scene': ['scn', 'tscn', 'escn'],
//     'x-godot-shader': ['gdshader'],
//     'x-gpx': ['gpx'],
//     'x-gpx+xml': ['gpx'],
//     'x-gramps-xml': ['gramps'],
//     'x-graphite': ['gra'],
//     'x-gtar': ['gtar', 'tar', 'gem'],
//     'x-gtk-builder': ['ui'],
//     'x-gz-font-linux-psf': ['psfgz'],
//     'x-gzdvi': ['dvigz'],
//     'x-gzip': ['gz'],
//     'x-gzpdf': ['pdfgz'],
//     'x-gzpostscript': ['psgz'],
//     'x-hdf': ['hdf', 'hdf4', 'h4', 'hdf5', 'h5'],
//     'x-hfe-file': ['hfe'],
//     'x-hfe-floppy-image': ['hfe'],
//     'x-httpd-php': ['php'],
//     'x-hwp': ['hwp'],
//     'x-hwt': ['hwt'],
//     'x-ica': ['ica'],
//     'x-install-instructions': ['install'],
//     'x-ips-patch': ['ips'],
//     'x-ipynb+json': ['ipynb'],
//     'x-iso9660-appimage': ['appimage'],
//     'x-iso9660-image': ['iso', 'iso9660'],
//     'x-it87': ['it87'],
//     'x-iwork-keynote-sffkey': ['key'],
//     'x-iwork-numbers-sffnumbers': ['numbers'],
//     'x-iwork-pages-sffpages': ['pages'],
//     'x-jar': ['jar'],
//     'x-java': ['class'],
//     'x-java-archive': ['jar'],
//     'x-java-archive-diff': ['jardiff'],
//     'x-java-class': ['class'],
//     'x-java-jce-keystore': ['jceks'],
//     'x-java-jnlp-file': ['jnlp'],
//     'x-java-keystore': ['jks', 'ks'],
//     'x-java-pack200': ['pack'],
//     'x-java-vm': ['class'],
//     'x-javascript': ['js', 'jsm', 'mjs'],
//     'x-jbuilder-project': ['jpr', 'jpx'],
//     'x-karbon': ['karbon'],
//     'x-kchart': ['chrt'],
//     'x-keepass2': ['kdbx'],
//     'x-kexi-connectiondata': ['kexic'],
//     'x-kexiproject-shortcut': ['kexis'],
//     'x-kexiproject-sqlite': ['kexi'],
//     'x-kexiproject-sqlite2': ['kexi'],
//     'x-kexiproject-sqlite3': ['kexi'],
//     'x-kformula': ['kfo'],
//     'x-killustrator': ['kil'],
//     'x-kivio': ['flw'],
//     'x-kontour': ['kon'],
//     'x-kpovmodeler': ['kpm'],
//     'x-kpresenter': ['kpr', 'kpt'],
//     'x-krita': ['kra', 'krz'],
//     'x-kspread': ['ksp'],
//     'x-kugar': ['kud'],
//     'x-kword': ['kwd', 'kwt'],
//     'x-latex': ['latex'],
//     'x-lha': ['lha', 'lzh'],
//     'x-lhz': ['lhz'],
//     'x-linguist': ['ts'],
//     'x-lmdb': ['mdb', 'lmdb'],
//     'x-lotus123': ['123', 'wk1', 'wk3', 'wk4', 'wks'],
//     'x-lrzip': ['lrz'],
//     'x-lrzip-compressed-tar': ['tarlrz', 'tlrz'],
//     'x-lua-bytecode': ['luac'],
//     'x-lyx': ['lyx'],
//     'x-lz4': ['lz4'],
//     'x-lz4-compressed-tar': ['tarlz4'],
//     'x-lzh-compressed': ['lzh', 'lha'],
//     'x-lzip': ['lz'],
//     'x-lzip-compressed-tar': ['tarlz'],
//     'x-lzma': ['lzma'],
//     'x-lzma-compressed-tar': ['tarlzma', 'tlz'],
//     'x-lzop': ['lzo'],
//     'x-lzpdf': ['pdflz'],
//     'x-m4': ['m4'],
//     'x-magicpoint': ['mgp'],
//     'x-makeself': ['run'],
//     'x-mame-chd': ['chd'],
//     'x-markaby': ['mab'],
//     'x-mathematica': ['nb'],
//     'x-mdb': ['mdb'],
//     'x-mie': ['mie'],
//     'x-mif': ['mif'],
//     'x-mimearchive': ['mhtml', 'mht'],
//     'x-mobi8-ebook': ['azw3', 'kfx'],
//     'x-mobipocket-ebook': ['prc', 'mobi'],
//     'x-modrinth-modpack+zip': ['mrpack'],
//     'x-ms-application': ['application'],
//     'x-ms-asx': ['asx', 'wax', 'wvx', 'wmx'],
//     'x-ms-dos-executable': ['exe'],
//     'x-ms-pdb': ['pdb'],
//     'x-ms-shortcut': ['lnk'],
//     'x-ms-wim': ['wim', 'swm'],
//     'x-ms-wmd': ['wmd'],
//     'x-ms-wmz': ['wmz'],
//     'x-ms-xbap': ['xbap'],
//     'x-msaccess': ['mdb'],
//     'x-msbinder': ['obd'],
//     'x-mscardfile': ['crd'],
//     'x-msclip': ['clp'],
//     'x-msdos-program': ['exe'],
//     'x-msdownload': ['exe', 'dll', 'com', 'bat', 'msi'],
//     'x-msexcel': ['xls', 'xlc', 'xll', 'xlm', 'xlw', 'xla', 'xlt', 'xld'],
//     'x-msi': ['msi'],
//     'x-msmediaview': ['mvb', 'm13', 'm14'],
//     'x-msmetafile': ['wmf', 'wmz', 'emf', 'emz'],
//     'x-msmoney': ['mny'],
//     'x-mspowerpoint': ['ppz', 'ppt', 'pps', 'pot'],
//     'x-mspublisher': ['pub'],
//     'x-msschedule': ['scd'],
//     'x-msterminal': ['trm'],
//     'x-mswinurl': ['url'],
//     'x-msword': ['doc'],
//     'x-mswrite': ['wri'],
//     'x-msx-rom': ['msx'],
//     'x-n64-rom': ['n64', 'z64', 'v64'],
//     'x-navi-animation': ['ani'],
//     'x-neo-geo-pocket-color-rom': ['ngc'],
//     'x-neo-geo-pocket-rom': ['ngp'],
//     'x-nes-rom': ['nes', 'nez', 'unf', 'unif'],
//     'x-netcdf': ['nc', 'cdf'],
//     'x-netshow-channel': ['nsc'],
//     'x-nintendo-3ds-executable': ['3dsx'],
//     'x-nintendo-3ds-rom': ['3ds', 'cci'],
//     'x-nintendo-ds-rom': ['nds'],
//     'x-ns-proxy-autoconfig': ['pac'],
//     'x-nuscript': ['nu'],
//     'x-nzb': ['nzb'],
//     'x-object': ['o', 'mod'],
//     'x-ogg': ['ogx'],
//     'x-oleo': ['oleo'],
//     'x-openvpn-profile': ['openvpn', 'ovpn'],
//     'x-openzim': ['zim'],
//     'x-pagemaker': ['p65', 'pm', 'pm6', 'pmd'],
//     'x-pak': ['pak'],
//     'x-palm-database': ['prc', 'pdb', 'pqa', 'oprc'],
//     'x-par2': ['PAR2', 'par2'],
//     'x-partial-download': ['wkdownload', 'crdownload', 'part'],
//     'x-pc-engine-rom': ['pce'],
//     'x-pcap': ['pcap', 'cap', 'dmp'],
//     'x-pdf': ['pdf'],
//     'x-perl': ['pl', 'pm', 'PL', 'al', 'perl', 'pod', 't'],
//     'x-photoshop': ['psd'],
//     'x-php': ['php', 'php3', 'php4', 'php5', 'phps'],
//     'x-pilot': ['prc', 'pdb'],
//     'x-pkcs12': ['p12', 'pfx'],
//     'x-pkcs7-certificates': ['p7b', 'spc'],
//     'x-pkcs7-certreqresp': ['p7r'],
//     'x-planperfect': ['pln'],
//     'x-pocket-word': ['psw'],
//     'x-pw': ['pw'],
//     'x-pyspread-bz-spreadsheet': ['pys'],
//     'x-pyspread-spreadsheet': ['pysu'],
//     'x-python-bytecode': ['pyc', 'pyo'],
//     'x-qed-disk': ['qed'],
//     'x-qemu-disk': ['qcow2', 'qcow'],
//     'x-qpress': ['qp'],
//     'x-qtiplot': ['qti', 'qtigz'],
//     'x-quattropro': ['wb1', 'wb2', 'wb3'],
//     'x-quicktime-media-link': ['qtl'],
//     'x-quicktimeplayer': ['qtl'],
//     'x-qw': ['qif'],
//     'x-rar': ['rar'],
//     'x-rar-compressed': ['rar'],
//     'x-raw-disk-image': ['raw-disk-image', 'img'],
//     'x-raw-disk-image-xz-compressed': ['raw-disk-imagexz', 'imgxz'],
//     'x-raw-floppy-disk-image': ['fd', 'qd'],
//     'x-redhat-package-manager': ['rpm'],
//     'x-reject': ['rej'],
//     'x-research-info-systems': ['ris'],
//     'x-rnc': ['rnc'],
//     'x-rpm': ['rpm'],
//     'x-ruby': ['rb'],
//     'x-sami': ['smi', 'sami'],
//     'x-sap-file': ['sap'],
//     'x-saturn-rom': ['iso'],
//     'x-sdp': ['sdp'],
//     'x-sea': ['sea'],
//     'x-sega-cd-rom': ['iso'],
//     'x-sega-pico-rom': ['iso'],
//     'x-sg1000-rom': ['sg'],
//     'x-sh': ['sh'],
//     'x-shar': ['shar'],
//     'x-shared-library-la': ['la'],
//     'x-sharedlib': ['so'],
//     'x-shellscript': ['sh'],
//     'x-shockwave-flash': ['swf', 'spl'],
//     'x-shorten': ['shn'],
//     'x-siag': ['siag'],
//     'x-silverlight-app': ['xap'],
//     'x-sit': ['sit'],
//     'x-sitx': ['sitx'],
//     'x-smaf': ['mmf', 'smaf'],
//     'x-sms-rom': ['sms'],
//     'x-snes-rom': ['sfc', 'smc'],
//     'x-source-rpm': ['srcrpm', 'spm'],
//     'x-spss-por': ['por'],
//     'x-spss-sav': ['sav', 'zsav'],
//     'x-spss-savefile': ['sav', 'zsav'],
//     'x-sql': ['sql'],
//     'x-sqlite2': ['sqlite2'],
//     'x-sqlite3': ['sqlite3'],
//     'x-srt': ['srt'],
//     'x-stuffit': ['sit'],
//     'x-stuffitx': ['sitx'],
//     'x-subrip': ['srt'],
//     'x-sv4cpio': ['sv4cpio'],
//     'x-sv4crc': ['sv4crc'],
//     'x-t3vm-image': ['t3'],
//     'x-t602': ['602'],
//     'x-tads': ['gam'],
//     'x-tar': ['tar', 'gtar', 'gem'],
//     'x-targa': ['tga', 'icb', 'tpic', 'vda', 'vst'],
//     'x-tarz': ['tarZ', 'taz'],
//     'x-tcl': ['tcl', 'tk'],
//     'x-tex': ['tex', 'ltx', 'sty', 'cls', 'dtx', 'ins', 'latex'],
//     'x-tex-gf': ['gf'],
//     'x-tex-pk': ['pk'],
//     'x-tex-tfm': ['tfm'],
//     'x-texinfo': ['texinfo', 'texi'],
//     'x-tga': ['tga', 'icb', 'tpic', 'vda', 'vst'],
//     'x-tgif': ['obj'],
//     'x-theme': ['theme'],
//     'x-thomson-cartridge-memo7': ['m7'],
//     'x-thomson-cassette': ['k7'],
//     'x-thomson-sap-image': ['sap'],
//     'x-tiled-tmx': ['tmx'],
//     'x-tiled-tsx': ['tsx'],
//     'x-trash': ['bak', 'old', 'sik'],
//     'x-trig': ['trig'],
//     'x-troff': ['tr', 'roff', 't'],
//     'x-troff-man': ['man'],
//     'x-tzo': ['tarlzo', 'tzo'],
//     'x-ufraw': ['ufraw'],
//     'x-ustar': ['ustar'],
//     'x-vdi-disk': ['vdi'],
//     'x-vhd-disk': ['vhd', 'vpc'],
//     'x-vhdx-disk': ['vhdx'],
//     'x-virtual-boy-rom': ['vb'],
//     'x-virtualbox-hdd': ['hdd'],
//     'x-virtualbox-ova': ['ova'],
//     'x-virtualbox-ovf': ['ovf'],
//     'x-virtualbox-vbox': ['vbox'],
//     'x-virtualbox-vbox-extpack': ['vbox-extpack'],
//     'x-virtualbox-vdi': ['vdi'],
//     'x-virtualbox-vhd': ['vhd', 'vpc'],
//     'x-virtualbox-vhdx': ['vhdx'],
//     'x-virtualbox-vmdk': ['vmdk'],
//     'x-vmdk-disk': ['vmdk'],
//     'x-vnd.kde.kexi': ['kexi'],
//     'x-wais-source': ['src'],
//     'x-wbfs': ['iso'],
//     'x-web-app-manifest+json': ['webapp'],
//     'x-wia': ['iso'],
//     'x-wii-iso-image': ['iso'],
//     'x-wii-rom': ['iso'],
//     'x-wii-wad': ['wad'],
//     'x-windows-themepack': ['themepack'],
//     'x-wmf': ['wmf'],
//     'x-wonderswan-color-rom': ['wsc'],
//     'x-wonderswan-rom': ['ws'],
//     'x-wordperfect': ['wp', 'wp4', 'wp5', 'wp6', 'wpd', 'wpp'],
//     'x-wpg': ['wpg'],
//     'x-wwf': ['wwf'],
//     'x-x509-ca-cert': ['der', 'crt', 'pem', 'cert'],
//     'x-xar': ['xar', 'pkg'],
//     'x-xbel': ['xbel'],
//     'x-xfig': ['fig'],
//     'x-xliff': ['xlf', 'xliff'],
//     'x-xliff+xml': ['xlf'],
//     'x-xpinstall': ['xpi'],
//     'x-xspf+xml': ['xspf'],
//     'x-xz': ['xz'],
//     'x-xz-compressed-tar': ['tarxz', 'txz'],
//     'x-xzpdf': ['pdfxz'],
//     'x-yaml': ['yaml', 'yml'],
//     'x-zip': ['zip', 'zipx'],
//     'x-zip-compressed': ['zip', 'zipx'],
//     'x-zip-compressed-fb2': ['fb2zip'],
//     'x-zmachine': ['z1', 'z2', 'z3', 'z4', 'z5', 'z6', 'z7', 'z8'],
//     'x-zoo': ['zoo'],
//     'x-zpaq': ['zpaq'],
//     'x-zstd-compressed-tar': ['tarzst', 'tzst'],
//     'xaml+xml': ['xaml'],
//     'xcap-att+xml': ['xav'],
//     'xcap-caps+xml': ['xca'],
//     'xcap-diff+xml': ['xdf'],
//     'xcap-el+xml': ['xel'],
//     'xcap-error+xml': ['xer'],
//     'xcap-ns+xml': ['xns'],
//     'xenc+xml': ['xenc'],
//     'xhtml+xml': ['xhtml', 'xht', 'html', 'htm'],
//     'xliff+xml': ['xlf', 'xliff'],
//     xml: ['xml', 'xsl', 'xsd', 'rng', 'xbl'],
//     'xml-dtd': ['dtd'],
//     'xml-external-parsed-entity': ['ent'],
//     'xop+xml': ['xop'],
//     'xproc+xml': ['xpl'],
//     xps: ['xps'],
//     'xslt+xml': ['xsl', 'xslt'],
//     'xspf+xml': ['xspf'],
//     'xv+xml': ['mxml', 'xhvml', 'xvml', 'xvm'],
//     yaml: ['yaml', 'yml'],
//     yang: ['yang'],
//     'yin+xml': ['yin'],
//     zip: ['zip', 'zipx'],
//     zlib: ['zz'],
//     zstd: ['zst'],
//   },
//   audio: {
//     '3gpp': ['3gpp', '3gp', '3ga'],
//     '3gpp-encrypted': ['3gp', '3gpp', '3ga'],
//     '3gpp2': ['3g2', '3gp2', '3gpp2'],
//     aac: ['aac', 'adts', 'ass'],
//     ac3: ['ac3'],
//     adpcm: ['adp'],
//     amr: ['amr'],
//     'amr-encrypted': ['amr'],
//     'amr-wb': ['awb'],
//     'amr-wb-encrypted': ['awb'],
//     annodex: ['axa'],
//     basic: ['au', 'snd'],
//     dff: ['dff'],
//     dsd: ['dsf'],
//     dsf: ['dsf'],
//     flac: ['flac'],
//     imelody: ['imy', 'ime'],
//     m3u: ['m3u', 'm3u8', 'vlc'],
//     m4a: ['m4a', 'f4a'],
//     midi: ['mid', 'midi', 'kar', 'rmi'],
//     'mobile-xmf': ['mxmf'],
//     mp2: ['mp2'],
//     mp3: ['mp3', 'mpga'],
//     mp4: ['m4a', 'mp4a', 'f4a'],
//     mpeg: ['mp3', 'mpga', 'mp2', 'mp2a', 'm2a', 'm3a'],
//     mpegurl: ['m3u', 'm3u8', 'vlc'],
//     ogg: ['ogg', 'oga', 'spx', 'opus'],
//     'prs.sid': ['sid', 'psid'],
//     s3m: ['s3m'],
//     scpls: ['pls'],
//     silk: ['sil'],
//     tta: ['tta'],
//     usac: ['loas', 'xhe'],
//     'vnd.audible': ['aa', 'aax'],
//     'vnd.audible.aax': ['aax'],
//     'vnd.audible.aaxc': ['aaxc'],
//     'vnd.dece.audio': ['uva', 'uvva'],
//     'vnd.digital-winds': ['eol'],
//     'vnd.dra': ['dra'],
//     'vnd.dts': ['dts'],
//     'vnd.dts.hd': ['dtshd'],
//     'vnd.lucent.voice': ['lvp'],
//     'vnd.m-realaudio': ['ra', 'rax'],
//     'vnd.ms-playready.media.pya': ['pya'],
//     'vnd.nokia.mobile-xmf': ['mxmf'],
//     'vnd.nuera.ecelp4800': ['ecelp4800'],
//     'vnd.nuera.ecelp7470': ['ecelp7470'],
//     'vnd.nuera.ecelp9600': ['ecelp9600'],
//     'vnd.rip': ['rip'],
//     'vnd.rn-realaudio': ['ra', 'rax'],
//     'vnd.wave': ['wav'],
//     vorbis: ['oga', 'ogg'],
//     wav: ['wav'],
//     wave: ['wav'],
//     webm: ['weba'],
//     wma: ['wma'],
//     'x-aac': ['aac', 'adts', 'ass'],
//     'x-aifc': ['aifc', 'aiffc'],
//     'x-aiff': ['aif', 'aiff', 'aifc'],
//     'x-aiffc': ['aifc', 'aiffc'],
//     'x-amzxml': ['amz'],
//     'x-annodex': ['axa'],
//     'x-ape': ['ape'],
//     'x-caf': ['caf'],
//     'x-dff': ['dff'],
//     'x-dsd': ['dsf'],
//     'x-dsf': ['dsf'],
//     'x-dts': ['dts'],
//     'x-dtshd': ['dtshd'],
//     'x-flac': ['flac'],
//     'x-flac+ogg': ['oga', 'ogg'],
//     'x-gsm': ['gsm'],
//     'x-hx-aac-adts': ['aac', 'adts', 'ass'],
//     'x-imelody': ['imy', 'ime'],
//     'x-iriver-pla': ['pla'],
//     'x-it': ['it'],
//     'x-m3u': ['m3u', 'm3u8', 'vlc'],
//     'x-m4a': ['m4a', 'f4a'],
//     'x-m4b': ['m4b', 'f4b'],
//     'x-m4r': ['m4r'],
//     'x-matroska': ['mka'],
//     'x-midi': ['mid', 'midi', 'kar'],
//     'x-minipsf': ['minipsf'],
//     'x-mo3': ['mo3'],
//     'x-mod': ['mod', 'ult', 'uni', 'm15', 'mtm', '669', 'med'],
//     'x-mp2': ['mp2'],
//     'x-mp3': ['mp3', 'mpga'],
//     'x-mp3-playlist': ['m3u', 'm3u8', 'vlc'],
//     'x-mpeg': ['mp3', 'mpga'],
//     'x-mpegurl': ['m3u', 'm3u8', 'vlc'],
//     'x-mpg': ['mp3', 'mpga'],
//     'x-ms-asx': ['asx', 'wax', 'wvx', 'wmx'],
//     'x-ms-wax': ['wax'],
//     'x-ms-wma': ['wma'],
//     'x-ms-wmv': ['wmv'],
//     'x-musepack': ['mpc', 'mpp', 'mp+'],
//     'x-ogg': ['oga', 'ogg', 'opus'],
//     'x-oggflac': ['oga', 'ogg'],
//     'x-opus+ogg': ['opus'],
//     'x-pn-audibleaudio': ['aa', 'aax'],
//     'x-pn-realaudio': ['ram', 'ra', 'rax'],
//     'x-pn-realaudio-plugin': ['rmp'],
//     'x-psf': ['psf'],
//     'x-psflib': ['psflib'],
//     'x-realaudio': ['ra'],
//     'x-rn-3gpp-amr': ['3gp', '3gpp', '3ga'],
//     'x-rn-3gpp-amr-encrypted': ['3gp', '3gpp', '3ga'],
//     'x-rn-3gpp-amr-wb': ['3gp', '3gpp', '3ga'],
//     'x-rn-3gpp-amr-wb-encrypted': ['3gp', '3gpp', '3ga'],
//     'x-s3m': ['s3m'],
//     'x-scpls': ['pls'],
//     'x-shorten': ['shn'],
//     'x-speex': ['spx'],
//     'x-speex+ogg': ['oga', 'ogg', 'spx'],
//     'x-stm': ['stm'],
//     'x-tak': ['tak'],
//     'x-tta': ['tta'],
//     'x-voc': ['voc'],
//     'x-vorbis': ['oga', 'ogg'],
//     'x-vorbis+ogg': ['oga', 'ogg'],
//     'x-wav': ['wav'],
//     'x-wavpack': ['wv', 'wvp'],
//     'x-wavpack-correction': ['wvc'],
//     'x-xi': ['xi'],
//     'x-xm': ['xm'],
//     'x-xmf': ['xmf'],
//     xm: ['xm'],
//     xmf: ['xmf'],
//   },
//   chemical: {
//     'x-cdx': ['cdx'],
//     'x-cif': ['cif'],
//     'x-cmdf': ['cmdf'],
//     'x-cml': ['cml'],
//     'x-csml': ['csml'],
//     'x-xyz': ['xyz'],
//   },
//   'flv-application': {
//     'octet-stream': ['flv'],
//   },
//   font: {
//     collection: ['ttc'],
//     otf: ['otf'],
//     ttf: ['ttf'],
//     woff: ['woff'],
//     woff2: ['woff2'],
//   },
//   image: {
//     aces: ['exr'],
//     apng: ['apng', 'png'],
//     astc: ['astc'],
//     avci: ['avci'],
//     avcs: ['avcs'],
//     avif: ['avif', 'avifs'],
//     'avif-sequence': ['avif', 'avifs'],
//     bmp: ['bmp', 'dib'],
//     cdr: ['cdr'],
//     cgm: ['cgm'],
//     'dicom-rle': ['drle'],
//     emf: ['emf'],
//     'fax-g3': ['g3'],
//     fits: ['fits', 'fit', 'fts'],
//     g3fax: ['g3'],
//     gif: ['gif'],
//     heic: ['heic', 'heif', 'hif'],
//     'heic-sequence': ['heics', 'heic', 'heif', 'hif'],
//     heif: ['heif', 'heic', 'hif'],
//     'heif-sequence': ['heifs', 'heic', 'heif', 'hif'],
//     hej2k: ['hej2'],
//     hsj2: ['hsj2'],
//     ico: ['ico'],
//     icon: ['ico'],
//     ief: ['ief'],
//     jls: ['jls'],
//     jp2: ['jp2', 'jpg2'],
//     jpeg: ['jpg', 'jpeg', 'jpe'],
//     jpeg2000: ['jp2', 'jpg2'],
//     'jpeg2000-image': ['jp2', 'jpg2'],
//     jph: ['jph'],
//     jphc: ['jhc'],
//     jpm: ['jpm', 'jpgm'],
//     jpx: ['jpx', 'jpf'],
//     jxl: ['jxl'],
//     jxr: ['jxr', 'hdp', 'wdp'],
//     jxra: ['jxra'],
//     jxrs: ['jxrs'],
//     jxs: ['jxs'],
//     jxsc: ['jxsc'],
//     jxsi: ['jxsi'],
//     jxss: ['jxss'],
//     ktx: ['ktx'],
//     ktx2: ['ktx2'],
//     openraster: ['ora'],
//     pdf: ['pdf'],
//     photoshop: ['psd'],
//     pjpeg: ['jpg', 'jpeg', 'jpe'],
//     png: ['png'],
//     'prs.btif': ['btif'],
//     'prs.pti': ['pti'],
//     psd: ['psd'],
//     qoi: ['qoi'],
//     rle: ['rle'],
//     sgi: ['sgi'],
//     svg: ['svg'],
//     'svg+xml': ['svg', 'svgz'],
//     'svg+xml-compressed': ['svgz', 'svggz'],
//     t38: ['t38'],
//     targa: ['tga', 'icb', 'tpic', 'vda', 'vst'],
//     tga: ['tga', 'icb', 'tpic', 'vda', 'vst'],
//     tiff: ['tif', 'tiff'],
//     'tiff-fx': ['tfx'],
//     'vnd.adobe.photoshop': ['psd'],
//     'vnd.airzip.accelerator.azv': ['azv'],
//     'vnd.dece.graphic': ['uvi', 'uvvi', 'uvg', 'uvvg'],
//     'vnd.djvu': ['djvu', 'djv'],
//     'vnd.djvu+multipage': ['djvu', 'djv'],
//     'vnd.dvb.subtitle': ['sub'],
//     'vnd.dwg': ['dwg'],
//     'vnd.dxf': ['dxf'],
//     'vnd.fastbidsheet': ['fbs'],
//     'vnd.fpx': ['fpx'],
//     'vnd.fst': ['fst'],
//     'vnd.fujixerox.edmics-mmr': ['mmr'],
//     'vnd.fujixerox.edmics-rlc': ['rlc'],
//     'vnd.microsoft.icon': ['ico'],
//     'vnd.mozilla.apng': ['apng', 'png'],
//     'vnd.ms-dds': ['dds'],
//     'vnd.ms-modi': ['mdi'],
//     'vnd.ms-photo': ['wdp', 'jxr', 'hdp'],
//     'vnd.net-fpx': ['npx'],
//     'vnd.pco.b16': ['b16'],
//     'vnd.rn-realpix': ['rp'],
//     'vnd.tencent.tap': ['tap'],
//     'vnd.valve.source.texture': ['vtf'],
//     'vnd.wap.wbmp': ['wbmp'],
//     'vnd.xiff': ['xif'],
//     'vnd.zbrush.pcx': ['pcx'],
//     webp: ['webp'],
//     wmf: ['wmf'],
//     'x-3ds': ['3ds'],
//     'x-adobe-dng': ['dng'],
//     'x-applix-graphics': ['ag'],
//     'x-bmp': ['bmp', 'dib'],
//     'x-bzeps': ['epsbz2', 'epsibz2', 'epsfbz2'],
//     'x-canon-cr2': ['cr2'],
//     'x-canon-cr3': ['cr3'],
//     'x-canon-crw': ['crw'],
//     'x-cdr': ['cdr'],
//     'x-cmu-raster': ['ras'],
//     'x-cmx': ['cmx'],
//     'x-compressed-xcf': ['xcfgz', 'xcfbz2'],
//     'x-dds': ['dds'],
//     'x-djvu': ['djvu', 'djv'],
//     'x-emf': ['emf'],
//     'x-eps': ['eps', 'epsi', 'epsf'],
//     'x-exr': ['exr'],
//     'x-fits': ['fits', 'fit', 'fts'],
//     'x-freehand': ['fh', 'fhc', 'fh4', 'fh5', 'fh7'],
//     'x-fuji-raf': ['raf'],
//     'x-gimp-gbr': ['gbr'],
//     'x-gimp-gih': ['gih'],
//     'x-gimp-pat': ['pat'],
//     'x-gzeps': ['epsgz', 'epsigz', 'epsfgz'],
//     'x-icb': ['tga', 'icb', 'tpic', 'vda', 'vst'],
//     'x-icns': ['icns'],
//     'x-ico': ['ico'],
//     'x-icon': ['ico'],
//     'x-iff': ['iff', 'ilbm', 'lbm'],
//     'x-ilbm': ['iff', 'ilbm', 'lbm'],
//     'x-jng': ['jng'],
//     'x-jp2-codestream': ['j2c', 'j2k', 'jpc'],
//     'x-jpeg2000-image': ['jp2', 'jpg2'],
//     'x-kodak-dcr': ['dcr'],
//     'x-kodak-k25': ['k25'],
//     'x-kodak-kdc': ['kdc'],
//     'x-lwo': ['lwo', 'lwob'],
//     'x-lws': ['lws'],
//     'x-macpaint': ['pntg'],
//     'x-minolta-mrw': ['mrw'],
//     'x-mrsid-image': ['sid'],
//     'x-ms-bmp': ['bmp', 'dib'],
//     'x-msod': ['msod'],
//     'x-nikon-nef': ['nef'],
//     'x-nikon-nrw': ['nrw'],
//     'x-olympus-orf': ['orf'],
//     'x-panasonic-raw': ['raw'],
//     'x-panasonic-raw2': ['rw2'],
//     'x-panasonic-rw': ['raw'],
//     'x-panasonic-rw2': ['rw2'],
//     'x-pcx': ['pcx'],
//     'x-pentax-pef': ['pef'],
//     'x-photo-cd': ['pcd'],
//     'x-photoshop': ['psd'],
//     'x-pict': ['pic', 'pct', 'pict', 'pict1', 'pict2'],
//     'x-portable-anymap': ['pnm'],
//     'x-portable-bitmap': ['pbm'],
//     'x-portable-graymap': ['pgm'],
//     'x-portable-pixmap': ['ppm'],
//     'x-psd': ['psd'],
//     'x-quicktime': ['qtif', 'qif'],
//     'x-rgb': ['rgb'],
//     'x-sgi': ['sgi'],
//     'x-sigma-x3f': ['x3f'],
//     'x-skencil': ['sk', 'sk1'],
//     'x-sony-arw': ['arw'],
//     'x-sony-sr2': ['sr2'],
//     'x-sony-srf': ['srf'],
//     'x-sun-raster': ['sun'],
//     'x-targa': ['tga', 'icb', 'tpic', 'vda', 'vst'],
//     'x-tga': ['tga', 'icb', 'tpic', 'vda', 'vst'],
//     'x-win-bitmap': ['cur'],
//     'x-win-metafile': ['wmf'],
//     'x-wmf': ['wmf'],
//     'x-xbitmap': ['xbm'],
//     'x-xcf': ['xcf'],
//     'x-xfig': ['fig'],
//     'x-xpixmap': ['xpm'],
//     'x-xpm': ['xpm'],
//     'x-xwindowdump': ['xwd'],
//     'x.djvu': ['djvu', 'djv'],
//   },
//   message: {
//     'disposition-notification': ['disposition-notification'],
//     global: ['u8msg'],
//     'global-delivery-status': ['u8dsn'],
//     'global-disposition-notification': ['u8mdn'],
//     'global-headers': ['u8hdr'],
//     rfc822: ['eml', 'mime'],
//     'vnd.wfa.wsc': ['wsc'],
//   },
//   model: {
//     '3mf': ['3mf'],
//     'gltf+json': ['gltf'],
//     'gltf-binary': ['glb'],
//     iges: ['igs', 'iges'],
//     mesh: ['msh', 'mesh', 'silo'],
//     mtl: ['mtl'],
//     obj: ['obj'],
//     'step+xml': ['stpx'],
//     'step+zip': ['stpz'],
//     'step-xml+zip': ['stpxz'],
//     stl: ['stl'],
//     'vnd.collada+xml': ['dae'],
//     'vnd.dwf': ['dwf'],
//     'vnd.gdl': ['gdl'],
//     'vnd.gtw': ['gtw'],
//     'vnd.mts': ['mts'],
//     'vnd.opengex': ['ogex'],
//     'vnd.parasolid.transmit.binary': ['x_b'],
//     'vnd.parasolid.transmit.text': ['x_t'],
//     'vnd.sap.vds': ['vds'],
//     'vnd.usdz+zip': ['usdz'],
//     'vnd.valve.source.compiled-map': ['bsp'],
//     'vnd.vtu': ['vtu'],
//     vrml: ['wrl', 'vrml', 'vrm'],
//     'x.stl-ascii': ['stl'],
//     'x.stl-binary': ['stl'],
//     'x3d+binary': ['x3db', 'x3dbz'],
//     'x3d+fastinfoset': ['x3db'],
//     'x3d+vrml': ['x3dv', 'x3dvz'],
//     'x3d+xml': ['x3d', 'x3dz'],
//     'x3d-vrml': ['x3dv'],
//   },
//   text: {
//     'cache-manifest': ['appcache', 'manifest'],
//     calendar: ['ics', 'ifb', 'vcs'],
//     coffeescript: ['coffee', 'litcoffee'],
//     crystal: ['cr'],
//     css: ['css'],
//     csv: ['csv'],
//     'csv-schema': ['csvs'],
//     directory: ['vcard', 'vcf', 'vct', 'gcrd'],
//     ecmascript: ['es'],
//     gedcom: ['ged', 'gedcom'],
//     'google-video-pointer': ['gvp'],
//     html: ['html', 'htm', 'shtml'],
//     ico: ['ico'],
//     jade: ['jade'],
//     javascript: ['js', 'jsm', 'mjs'],
//     jsx: ['jsx'],
//     julia: ['jl'],
//     less: ['less'],
//     markdown: ['md', 'markdown', 'mkd'],
//     mathml: ['mml'],
//     mdx: ['mdx'],
//     n3: ['n3'],
//     org: ['org'],
//     plain: ['txt', 'text', 'conf', 'def', 'list', 'log', 'in', 'ini', 'asc'],
//     'prs.lines.tag': ['dsc'],
//     rdf: ['rdf', 'rdfs', 'owl'],
//     richtext: ['rtx'],
//     rss: ['rss'],
//     rtf: ['rtf'],
//     rust: ['rs'],
//     sgml: ['sgml', 'sgm'],
//     shex: ['shex'],
//     slim: ['slim', 'slm'],
//     spdx: ['spdx'],
//     spreadsheet: ['sylk', 'slk'],
//     stylus: ['stylus', 'styl'],
//     'tab-separated-values': ['tsv'],
//     tcl: ['tcl', 'tk'],
//     troff: ['t', 'tr', 'roff', 'man', 'me', 'ms'],
//     turtle: ['ttl'],
//     'uri-list': ['uri', 'uris', 'urls'],
//     vbs: ['vbs'],
//     vbscript: ['vbs'],
//     vcard: ['vcard', 'vcf', 'vct', 'gcrd'],
//     'vnd.curl': ['curl'],
//     'vnd.curl.dcurl': ['dcurl'],
//     'vnd.curl.mcurl': ['mcurl'],
//     'vnd.curl.scurl': ['scurl'],
//     'vnd.dvb.subtitle': ['sub'],
//     'vnd.familysearch.gedcom': ['ged', 'gedcom'],
//     'vnd.fly': ['fly'],
//     'vnd.fmi.flexstor': ['flx'],
//     'vnd.graphviz': ['gv', 'dot'],
//     'vnd.in3d.3dml': ['3dml'],
//     'vnd.in3d.spot': ['spot'],
//     'vnd.qt.linguist': ['ts'],
//     'vnd.rn-realtext': ['rt'],
//     'vnd.senx.warpscript': ['mc2'],
//     'vnd.sun.j2me.app-descriptor': ['jad'],
//     'vnd.trolltech.linguist': ['ts'],
//     'vnd.wap.wml': ['wml'],
//     'vnd.wap.wmlscript': ['wmls'],
//     vtt: ['vtt'],
//     'x-adasrc': ['adb', 'ads'],
//     'x-asm': ['s', 'asm'],
//     'x-bibtex': ['bib'],
//     'x-blueprint': ['blp'],
//     'x-c': ['c', 'cc', 'cxx', 'cpp', 'h', 'hh', 'dic'],
//     'x-c++hdr': ['hh', 'hp', 'hpp', 'h++', 'hxx'],
//     'x-c++src': ['cpp', 'cxx', 'cc', 'C', 'c++'],
//     'x-chdr': ['h'],
//     'x-cmake': ['cmake'],
//     'x-cobol': ['cbl', 'cob'],
//     'x-comma-separated-values': ['csv'],
//     'x-common-lisp': ['asd', 'fasl', 'lisp', 'ros'],
//     'x-component': ['htc'],
//     'x-crystal': ['cr'],
//     'x-csharp': ['cs'],
//     'x-csrc': ['c'],
//     'x-csv': ['csv'],
//     'x-dart': ['dart'],
//     'x-dbus-service': ['service'],
//     'x-dcl': ['dcl'],
//     'x-devicetree-binary': ['dtb'],
//     'x-devicetree-source': ['dts', 'dtsi'],
//     'x-diff': ['diff', 'patch'],
//     'x-dsl': ['dsl'],
//     'x-dsrc': ['d', 'di'],
//     'x-dtd': ['dtd'],
//     'x-eiffel': ['e', 'eif'],
//     'x-elixir': ['ex', 'exs'],
//     'x-emacs-lisp': ['el'],
//     'x-erlang': ['erl'],
//     'x-fish': ['fish'],
//     'x-fortran': ['f', 'for', 'f77', 'f90', 'f95'],
//     'x-gcode-gx': ['gx'],
//     'x-genie': ['gs'],
//     'x-gettext-translation': ['po'],
//     'x-gettext-translation-template': ['pot'],
//     'x-gherkin': ['feature'],
//     'x-go': ['go'],
//     'x-google-video-pointer': ['gvp'],
//     'x-gradle': ['gradle'],
//     'x-groovy': ['groovy', 'gvy', 'gy', 'gsh'],
//     'x-handlebars-template': ['hbs'],
//     'x-haskell': ['hs'],
//     'x-idl': ['idl'],
//     'x-imelody': ['imy', 'ime'],
//     'x-iptables': ['iptables'],
//     'x-java': ['java'],
//     'x-java-source': ['java'],
//     'x-kaitai-struct': ['ksy'],
//     'x-kotlin': ['kt'],
//     'x-ldif': ['ldif'],
//     'x-lilypond': ['ly'],
//     'x-literate-haskell': ['lhs'],
//     'x-log': ['log'],
//     'x-lua': ['lua'],
//     'x-lyx': ['lyx'],
//     'x-makefile': ['mk', 'mak'],
//     'x-markdown': ['md', 'mkd', 'markdown'],
//     'x-matlab': ['m'],
//     'x-microdvd': ['sub'],
//     'x-moc': ['moc'],
//     'x-modelica': ['mo'],
//     'x-mof': ['mof'],
//     'x-mpl2': ['mpl'],
//     'x-mpsub': ['sub'],
//     'x-mrml': ['mrml', 'mrl'],
//     'x-ms-regedit': ['reg'],
//     'x-mup': ['mup', 'not'],
//     'x-nfo': ['nfo'],
//     'x-nim': ['nim'],
//     'x-nimscript': ['nims', 'nimble'],
//     'x-nu': ['nu'],
//     'x-objc++src': ['mm'],
//     'x-objcsrc': ['m'],
//     'x-ocaml': ['ml', 'mli'],
//     'x-ocl': ['ocl'],
//     'x-octave': ['m'],
//     'x-ooc': ['ooc'],
//     'x-opencl-src': ['cl'],
//     'x-opml': ['opml'],
//     'x-opml+xml': ['opml'],
//     'x-org': ['org'],
//     'x-pascal': ['p', 'pas'],
//     'x-patch': ['diff', 'patch'],
//     'x-perl': ['pl', 'PL', 'pm', 'al', 'perl', 'pod', 't'],
//     'x-po': ['po'],
//     'x-pot': ['pot'],
//     'x-processing': ['pde'],
//     'x-python': ['py', 'pyx', 'wsgi'],
//     'x-python3': ['py', 'py3', 'py3x', 'pyi'],
//     'x-qml': ['qml', 'qmltypes', 'qmlproject'],
//     'x-reject': ['rej'],
//     'x-rpm-spec': ['spec'],
//     'x-rst': ['rst'],
//     'x-sagemath': ['sage'],
//     'x-sass': ['sass'],
//     'x-scala': ['scala', 'sc'],
//     'x-scheme': ['scm', 'ss'],
//     'x-scss': ['scss'],
//     'x-setext': ['etx'],
//     'x-sfv': ['sfv'],
//     'x-sh': ['sh'],
//     'x-sql': ['sql'],
//     'x-ssa': ['ssa', 'ass'],
//     'x-subviewer': ['sub'],
//     'x-suse-ymp': ['ymp'],
//     'x-svhdr': ['svh'],
//     'x-svsrc': ['sv'],
//     'x-systemd-unit': [
//       'automount',
//       'device',
//       'mount',
//       'path',
//       'scope',
//       'service',
//       'slice',
//       'socket',
//       'swap',
//       'target',
//       'timer',
//     ],
//     'x-tcl': ['tcl', 'tk'],
//     'x-tex': ['tex', 'ltx', 'sty', 'cls', 'dtx', 'ins', 'latex'],
//     'x-texinfo': ['texi', 'texinfo'],
//     'x-troff': ['tr', 'roff', 't'],
//     'x-troff-me': ['me'],
//     'x-troff-mm': ['mm'],
//     'x-troff-ms': ['ms'],
//     'x-twig': ['twig'],
//     'x-txt2tags': ['t2t'],
//     'x-typst': ['typ'],
//     'x-uil': ['uil'],
//     'x-uuencode': ['uu', 'uue'],
//     'x-vala': ['vala', 'vapi'],
//     'x-vcalendar': ['vcs', 'ics'],
//     'x-vcard': ['vcf', 'vcard', 'vct', 'gcrd'],
//     'x-verilog': ['v'],
//     'x-vhdl': ['vhd', 'vhdl'],
//     'x-xmi': ['xmi'],
//     'x-xslfo': ['fo', 'xslfo'],
//     'x-yaml': ['yaml', 'yml'],
//     'x.gcode': ['gcode'],
//     xml: ['xml', 'xbl', 'xsd', 'rng'],
//     'xml-external-parsed-entity': ['ent'],
//     yaml: ['yaml', 'yml'],
//   },
//   video: {
//     '3gp': ['3gp', '3gpp', '3ga'],
//     '3gpp': ['3gp', '3gpp', '3ga'],
//     '3gpp-encrypted': ['3gp', '3gpp', '3ga'],
//     '3gpp2': ['3g2', '3gp2', '3gpp2'],
//     annodex: ['axv'],
//     avi: ['avi', 'avf', 'divx'],
//     divx: ['avi', 'avf', 'divx'],
//     dv: ['dv'],
//     fli: ['fli', 'flc'],
//     flv: ['flv'],
//     h261: ['h261'],
//     h263: ['h263'],
//     h264: ['h264'],
//     'iso.segment': ['m4s'],
//     jpeg: ['jpgv'],
//     jpm: ['jpm', 'jpgm'],
//     mj2: ['mj2', 'mjp2'],
//     mp2t: ['ts', 'm2t', 'm2ts', 'mts', 'cpi', 'clpi', 'mpl', 'mpls', 'bdm', 'bdmv'],
//     mp4: ['mp4', 'mp4v', 'mpg4', 'm4v', 'f4v', 'lrv'],
//     'mp4v-es': ['mp4', 'm4v', 'f4v', 'lrv'],
//     mpeg: ['mpeg', 'mpg', 'mpe', 'm1v', 'm2v', 'mp2', 'vob'],
//     'mpeg-system': ['mpeg', 'mpg', 'mp2', 'mpe', 'vob'],
//     msvideo: ['avi', 'avf', 'divx'],
//     ogg: ['ogv', 'ogg'],
//     quicktime: ['mov', 'qt', 'moov', 'qtvr'],
//     vivo: ['viv', 'vivo'],
//     'vnd.avi': ['avi', 'avf', 'divx'],
//     'vnd.dece.hd': ['uvh', 'uvvh'],
//     'vnd.dece.mobile': ['uvm', 'uvvm'],
//     'vnd.dece.pd': ['uvp', 'uvvp'],
//     'vnd.dece.sd': ['uvs', 'uvvs'],
//     'vnd.dece.video': ['uvv', 'uvvv'],
//     'vnd.divx': ['avi', 'avf', 'divx'],
//     'vnd.dvb.file': ['dvb'],
//     'vnd.fvt': ['fvt'],
//     'vnd.mpegurl': ['mxu', 'm4u', 'm1u'],
//     'vnd.ms-playready.media.pyv': ['pyv'],
//     'vnd.radgamettools.bink': ['bik', 'bk2'],
//     'vnd.radgamettools.smacker': ['smk'],
//     'vnd.rn-realvideo': ['rv', 'rvx'],
//     'vnd.uvvu.mp4': ['uvu', 'uvvu'],
//     'vnd.vivo': ['viv', 'vivo'],
//     'vnd.youtube.yt': ['yt'],
//     webm: ['webm'],
//     'x-anim': ['anim1', 'anim2', 'anim3', 'anim4', 'anim5', 'anim6', 'anim7', 'anim8', 'anim9', 'animj'],
//     'x-annodex': ['axv'],
//     'x-avi': ['avi', 'avf', 'divx'],
//     'x-f4v': ['f4v'],
//     'x-fli': ['fli', 'flc'],
//     'x-flic': ['fli', 'flc'],
//     'x-flv': ['flv'],
//     'x-javafx': ['fxm'],
//     'x-m4v': ['m4v', 'mp4', 'f4v', 'lrv'],
//     'x-matroska': ['mkv', 'mk3d', 'mks'],
//     'x-matroska-3d': ['mk3d'],
//     'x-mjpeg': ['mjpeg', 'mjpg'],
//     'x-mng': ['mng'],
//     'x-mpeg': ['mpeg', 'mpg', 'mp2', 'mpe', 'vob'],
//     'x-mpeg-system': ['mpeg', 'mpg', 'mp2', 'mpe', 'vob'],
//     'x-mpeg2': ['mpeg', 'mpg', 'mp2', 'mpe', 'vob'],
//     'x-mpegurl': ['m1u', 'm4u', 'mxu'],
//     'x-ms-asf': ['asf', 'asx'],
//     'x-ms-asf-plugin': ['asf'],
//     'x-ms-vob': ['vob'],
//     'x-ms-wax': ['asx', 'wax', 'wvx', 'wmx'],
//     'x-ms-wm': ['wm', 'asf'],
//     'x-ms-wmv': ['wmv'],
//     'x-ms-wmx': ['wmx', 'asx', 'wax', 'wvx'],
//     'x-ms-wvx': ['wvx', 'asx', 'wax', 'wmx'],
//     'x-msvideo': ['avi', 'avf', 'divx'],
//     'x-nsv': ['nsv'],
//     'x-ogg': ['ogv', 'ogg'],
//     'x-ogm': ['ogm'],
//     'x-ogm+ogg': ['ogm'],
//     'x-real-video': ['rv', 'rvx'],
//     'x-sgi-movie': ['movie'],
//     'x-smv': ['smv'],
//     'x-theora': ['ogg'],
//     'x-theora+ogg': ['ogg'],
//   },
//   'x-conference': {
//     'x-cooltalk': ['ice'],
//   },
//   'x-epoc': {
//     'x-sisx-app': ['sisx'],
//   },
//   'zz-application': {
//     'zz-winassoc-123': ['123', 'wk1', 'wk3', 'wk4', 'wks'],
//     'zz-winassoc-cab': ['cab'],
//     'zz-winassoc-cdr': ['cdr'],
//     'zz-winassoc-doc': ['doc'],
//     'zz-winassoc-hlp': ['hlp'],
//     'zz-winassoc-mdb': ['mdb'],
//     'zz-winassoc-uu': ['uue'],
//     'zz-winassoc-xls': ['xls', 'xlc', 'xll', 'xlm', 'xlw', 'xla', 'xlt', 'xld'],
//   },
// }
